### ISSUE TITLE
Limit the number of characters in date input

### ISSUE THREAD

**Issue by AnveshR7** [wojtekmaj/react-date-picker#100]
Can we limit the characters in the input for day/month/year. 
for example for day and month we cannot type more than 2 characters( also for the year )

**Comment by Raknison123** [comment]
I would also appreciate that feature. However, in a first step the year could be limited to 4 characters if that's easier to implement.

**Comment by marcoancona** [comment]
I am also very interested in this. I think the UX would improve a lot preventing surely-invalid strings to be entered. My proposal: https://github.com/wojtekmaj/react-date-picker/pull/115

**Comment by wojtekmaj** [comment]
Duplicate of #44
