### ISSUE TITLE
Highlight a date

### ISSUE THREAD

**Issue by bdpaulo** [wojtekmaj/react-date-picker#105]
Sorry about my english..
I'm using the component on a bus tickets e-commerce and i need to highlight a previous selected date, how to do?

**Comment by wojtekmaj** [comment]
Hi there,
React-Date-Picker uses [React-Calendar](/wojtekmaj/react-calendar) under the hood for displaying the calendar. You can look at the docs there and I think `tileClassName` will be something for you.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
