### ISSUE TITLE
Calendar opens above input within absolute positioned element

### ISSUE THREAD

**Issue by mariusrak** [wojtekmaj/react-date-picker#110]
I use the datepicker component inside few absolutelly positioned elements and it opens above the input. It gets the `react-date-picker__calendar--above-label` class. When no parent has set position absolute, it works correctly, but when at least one parent, wherever in path has absolute position it goes above. Is it bug or shoudl/can I control it somehow?
Thanks.

**Comment by uzairjan** [comment]
same problem.

**Comment by wojtekmaj** [comment]
Hmmm, I tried to reproduce it in my test suite by applying `position: absolute` to a `<form>` which is React-Date-Picker's parent, and I had no luck reproducing this. Would you share your minimal reproduction with me?

**Comment by mariusrak** [comment]
I've tested the fix, but it didn't help. I guess the problem is not necessary with the `position: absolute` but maybe with `top: 0;bottom: 0;`. Can you please upload your reproduction and I will modify it to match my set-up. Thanks.

**Comment by wojtekmaj** [comment]
Did you? I didn't release the new version just yet.

[React-Fit](/wojtekmaj/react-fit) uses a function called [findScrollContainer](/wojtekmaj/react-fit/blob/master/src/Fit.jsx#L13-L28) to, well, find the nearest scroll container. It is this element we later detect collisions with, so it shouldn't have anything to do with `position: absolute`, actually.

Perhaps you could play with React-Fit to replicate your use case?
