### ISSUE TITLE
Altering minDate/maxDate does not update Navigation bar in Calendar

### ISSUE THREAD

**Issue by jmsgrima-gig** [wojtekmaj/react-date-picker#111]
I am using two Datepickers as a **from** and **to** range, user is allowed to select a range of a maximum of 60 days. Therefore, if user selects 01/08/2018 as the **from** date, the **to** date will have a **minDate** of 01/08/2018 and the **maxDate** will be set to 30/09/2018.

The **to** date has `minDate` set to the **from** date in the `render` function.

`componentDidUpdate` also checks whether the difference between the **from** and **to** date is larger than 60 days, if so the **to** date is set to 3 days more than the **from** date.

Even though the `minDate` prop is updated, the calendar does not seem to update the range when changing the **from** date to a previous month.

**Example:**

**On load:**

**From:** 21/10/2018, **To:** 24/10/2018

Changing **from** to 01/09/2018, updates **to** `minDate` to 01/09/2018 but the calendar does not enable the previous arrow to navigate to September.

If `componentDidUpdate` triggers the 60 days difference (for example selecting August), ranges work again. However the issue happens again upon selecting the previous month (selecting July).

It does work at times but it's not consistent.

**Screenshot**:

![image](https://user-images.githubusercontent.com/43986514/47452833-6f462100-d7cb-11e8-9f78-d9186fe282d0.png)

I managed to replicate this issue here: https://stackblitz.com/edit/react-e9tkt2

**Comment by jmsgrima-gig** [comment]
Small update :)

I'm noticing that the previous month button remains disabled until navigating months in the **to** calendar.

**For example:**

1. Change **from** date to 01/08/2018
2. Change **to** date to 10/08/2018
3. Update **from** date to 14/07/2018
4. Previous button is disabled in the **to** calendar
5. Navigating to September and back to August should enable previous button to July

**Comment by jmsgrima-gig** [comment]
So I went through the code a bit and noticed that `shouldComponentUpdate` in the Navigation component checks if `activeStartDate`, `locale` and `view` have updated, not `minDate` or `maxDate`.

I solved it by updating the `locale` onChange of the date picker, it's obviously a bit of a hack but it works.

**Comment by wojtekmaj** [comment]
Oh! Thank you for the report. I will track this under an issue mentioned above in React-Calendar package which React-Date-Picker uses. :) If you'd like to follow the progress on this, please see this issue.

**Comment by wojtekmaj** [comment]
React-Calendar v2.17.5 is out. You can update it manually in your repository, and it will also be included in the next React-Date-Picker release. Thank you for the report once again!
