### ISSUE TITLE
Custom prev/next arrows in the Calendar

### ISSUE THREAD

**Issue by yyynnn** [wojtekmaj/react-date-picker#113]
Provide the ability to inject custom arrow icons (as svg, text, etc.)

**Comment by wojtekmaj** [comment]
Arrows for Calendar? Check [React-Calendar](/wojtekmaj/react-calendar) docs on how to do it, you can pass every prop to DatePicker and it will be passed to the Calendar.

**Comment by yyynnn** [comment]
Cool, thanks! Didn't notice that in the readme
