### ISSUE TITLE
How to set Sunday as the first column in the calendar?

### ISSUE THREAD

**Issue by ChromeHearts** [wojtekmaj/react-date-picker#117]
Somehow my calendar is showing monday as the first column and sunday as the last column.  How can I have Sunday as the first column in a more conventional way?  Thanks!

My calendar
![screen shot 2018-11-12 at 4 00 44 pm](https://user-images.githubusercontent.com/5397127/48375058-aa35c900-e694-11e8-9b46-4550a2b458b8.png)

**Comment by wojtekmaj** [comment]
Calendar layout relies on locale settings. You should use `locale` that uses a calendar which starts on Sunday, for example `en-US`.

**Comment by ChromeHearts** [comment]
Thank you very much!  It worked like a charm!

**Comment by indiecollin** [comment]
Is there anything else I need to do besides set the locale prop on the DatePicker component? Currently when I try to set it to "en_US" Monday is still the first column. I've been able to get the format of the date to change using different locales, but not the day columns.

**Comment by wojtekmaj** [comment]
@indiecollin [IETF_language_tag](https://en.wikipedia.org/wiki/IETF_language_tag) is `xx-XX` not `xx_XX`.

**Comment by indiecollin** [comment]
@wojtekmaj sorry that was a typo from my comment. I have been trying it with the format xx-XX and it doesn't work.
