### ISSUE TITLE
TypeError: cannot read property '0' of null with Arabic numbers

### ISSUE THREAD

**Issue by aghoneim92** [wojtekmaj/react-date-picker#118]
When setting the locale to 'ar-EG', the placeholder property of the DateInput class uses arabic numerals. This causes this logic to fail: `this.formatDate(date, locale).replace('2017', 'year').replace('12', 'month').replace('11', 'day')` because the numbers do not match, so they don't get replaced.
Consequently, the `renderCustomInputs` function fails on matching the placeholder pattern (which it expects to be `day/month/year` but instead receives `٢٠١٧/١١/١١`). I am willing to work on a fix and would love to have it merged as soon as humanly possible :-)

**Comment by wojtekmaj** [comment]
Oh boy! I've never thought being a maintainer of React-Date-Picker would be such an adventure with so many different cultures :D Is it even possible to do a number input that uses Arabic numbers?

I'd love to see a PR fixing this, and you have all the help I can offer!

**Comment by aghoneim92** [comment]
@wojtekmaj I'm using your component in coding a computer system for a rehab center I'm currently 'serving time' in :D so yes your efforts have led to the weirdest kinds of use cases I would say!

My problem is with matching any kind of digit in any language, I'm sure Japanese and other languages might have different symbols for numbers as well.

Using the regex `/\d/` is only matching english numerals, so this is where I'm currently stuck.
Any ideas?

**Comment by aghoneim92** [comment]
I figured out a hack around this by using Number.prototype.toLocaleString() and passing the same locale used in the date!

**Comment by wojtekmaj** [comment]
@aghoneim92 Kindly check if `master` behaves well for you :)

BTW, `toLocaleString()` was not a hack, it was a very well done solution!

Now I'm struggling to figure out if there is a way to have non-latin numbers in input fields, since your fix "only" causes the inputs to appear, but they are still not properly formatter numbers 🤔
