### ISSUE TITLE
Clicking on a date separator doesn't open the calendar.

### ISSUE THREAD

**Issue by nikolai-tenev** [wojtekmaj/react-date-picker#120]
First of all - great component!

When I click on the date separators nothing happens. I think the expected behavior is for the calendar to appear. Not sure though, maybe this was intended?

**Comment by wojtekmaj** [comment]
Fixed via a244d4d4219a33384dbab1f37043f664eb8e3038 in this repo and via others in others 😄

**Comment by wojtekmaj** [comment]
Duplicate of #114
