### ISSUE TITLE
An invalid form control is not focusable

### ISSUE THREAD

**Issue by juodikis** [wojtekmaj/react-date-picker#122]
When you make a date-picker a required and try to submit form, Chrome puts an error 
`An invalid form control with name='date' is not focusable.`

This happens because `NativeInput`is first and it's visibility is hidden. 

> Chrome wants to focus on a control that is required but still empty so that it can pop up the message 'Please fill out this field'. However, if the control is hidden at the point that Chrome wants to pop up the message, that is at the time of form submission, Chrome can't focus on the control because it is hidden, therefore the form won't submit.

Possible solution could be either remove `required` attribute from `NativeInput` or move it after `CustomInputs`.

First option is self explanatory. Second solution would focus day input and when it's filled, automatically `NativeInput` would be filled and valid.

**Comment by wojtekmaj** [comment]
Both Chrome and Firefox correctly focus on the first available input inside React-Date-Picker so this will be wontfix.
