### ISSUE TITLE
onBlur is not triggered after selecting month

### ISSUE THREAD

**Issue by emibcn** [wojtekmaj/react-date-picker#123]
Navigating up to months or year selection, and then clicking outside the calendar **does** fires the `onBlur` event. But navigating to century selection or down to the rest of selectors (including day), clicking outside the calendar **does not** fires the `onBlur` event.

Note the difference between _navigating up_ (after clicking title) and _navigating down_ (after selecting an element).

**Comment by wojtekmaj** [comment]
The reason why onBlur is not fired is that you click on a button that navigates up, and your focus stays on this button. Once you go up to century view, this button is disabled and as such `onBlur` will not fire.

**Comment by emibcn** [comment]
Ah, thanks for the help. I thought the component would behave as a black box:
- Triggering `onFocus` when any of its elements triggers `onFocus` and it comes from outside the component
- Triggering `onBlur` when some of its elements triggers `onBlur` and it goes outside the component

Wouldn't it be a more intuitive approach?

**Comment by wojtekmaj** [comment]
I agree that it may be a simpler approach, but at the same time, it may be limiting. Any listeners you attach to React-Date-Picker are attached to its root element and behave very similar to the way they would behave if you wrapped React-Date-Picker in a `<div>` and attach all the listeners to it. The developers might want to have a listener that would react to blurring/focusing a specific element and/or a button, and I wouldn't like to take this option away from them. The idea of reimplementing the platform is something I'm not signing up for. :) 

Thanks for your input!
