### ISSUE TITLE
Formate

### ISSUE THREAD

**Issue by alokKumarSingh89** [wojtekmaj/react-date-picker#127]
Now able to change date format.
Like i want format in DD/MM/YYYY but you this taking MM/DD/YYYY.

Can you help me.

**Comment by wojtekmaj** [comment]
Duplicate of #40. See also #90.

**Comment by wojtekmaj** [comment]
Hi everyone,
React-Date-Picker 7.5.0 is out and supports `format` prop! Please refer to README for more details and list of supported tokens.

Happy coding!
