### ISSUE TITLE
Writing dates without jumping between date/month/year fields

### ISSUE THREAD

**Issue by cragia** [wojtekmaj/react-date-picker#128]
Hello!
I was asked if it's possible to be "faster" in writing a date.
Right now, if I want to use the keyboard to write the date, if I for example want to insert the date 12/03/2019, I need to type: 12 *tab* 03 *tab* 2019... but some users of some other environment are really use to do it faster, like writing 12032019. This because usually they have an automatic focus after 2 digits on the first input and after other 2 digits on the second input...
I would like to do the same thing, but obviously the component doesn't let me, I didn't find a way to have an event after every digit I press...

Can I do it some other way?

thank you.

**Comment by wojtekmaj** [comment]
You can write 12/03/2019 (using the symbol that separates the date on the screen) to write the dates :) But I think this is a legitimate improvement, let's do this!

**Comment by AndreaBeggiato** [comment]
#131 implement this feature

**Comment by daedalus28** [comment]
This will be a huge help to usability 👍
