### ISSUE TITLE
Chrome shows autocomplete menu on the month/day/year input

### ISSUE THREAD

**Issue by dozoisch** [wojtekmaj/react-date-picker#129]
Chrome shows an autocomplete menu on the month/day/year input and I noticed that none of these input have autocomplete="off".

I can do a PR to add autocomplete="off" to DayInput/MonthInput/YearInput. What do you think? 

![image](https://user-images.githubusercontent.com/4422516/50938885-2ea38e80-142f-11e9-9282-0cf37678ddf9.png)

Sorry if the image is cut early, I wanted to hide the data in the menu. The second menu on top of the calendar is chrome's autocomplete.

**Comment by dozoisch** [comment]
@wojtekmaj thanks so much for the fast turnaround! Looking forward for the next publish

**Comment by dozoisch** [comment]
@wojtekmaj would it be possible to cut a version with this fix? That would be much appreciated thank you :)!

**Comment by wojtekmaj** [comment]
Naaaah, a full release is better :D 7.2.0 is out, enjoy! :)

**Comment by dozoisch** [comment]
@wojtekmaj thank you so much!  :)
