### ISSUE TITLE
change placement position of datepicker?

### ISSUE THREAD

**Issue by efendyklb** [wojtekmaj/react-date-picker#132]
Is there a way to change placement position of datepicker? when I focus on the input the calendar container always show at the top of the text input, i wanna fix the position always at bottom

**Comment by Joesepherus** [comment]
Try adding
```
.react-date-picker__calendar--above-label {
    top: 100%
}
```
should work. But yeah would be nice if we had some prop to change the position.

**Comment by wojtekmaj** [comment]
Duplicate of #62
