### ISSUE TITLE
Different languages in browsers

### ISSUE THREAD

**Issue by AnatolyZhuravlev** [wojtekmaj/react-date-picker#136]
When I open page in Google Chrome or Opera I see date-picker on my language with my country's date format: "dd.mm.yyyy"
![2019-02-17 22-33-27](https://user-images.githubusercontent.com/31756328/52916695-8c67a800-3304-11e9-975c-a75f07f5db31.png)
But when I open page in Mozila Firefox I see English language and date format: "mm/dd/yyyy".
![2019-02-17 22-37-35](https://user-images.githubusercontent.com/31756328/52916701-a608ef80-3304-11e9-967c-3e796d126689.png)

Why it happening and how fix it?

**Comment by wojtekmaj** [comment]
Hi,
I use [Get-User-Locale](/wojtekmaj/get-user-locale) to get user's preferred language in a form of an IETF language tag, based on all available sources.

Reasons for that could be:
1. Most likely - a preference in Firefox settings is set in a way to prefer English over Russian.
2. Less likely - bug in Get-User-Locale

Get-User-Locale is not a rocket science, so you can check what's going on in your case quite easily:
https://github.com/wojtekmaj/get-user-locale/blob/master/src/entry.js#L21-L39

**Comment by wojtekmaj** [comment]
Hi @AnatolyZhuravlev,
do you still need help with this issue?

**Comment by AnatolyZhuravlev** [comment]
No, I don't. Thank you
