### ISSUE TITLE
Calendar not opening  when overflow: hidden 

### ISSUE THREAD

**Issue by prasher-ayce** [wojtekmaj/react-date-picker#137]
When over flow is hidden for scroll bar calendar  not opening.
Any work around this issue?

**Comment by wojtekmaj** [comment]
Hi!
Actually, when you were writing this, React-Date-Picker had a new calendar positioning system implemented, but not released just yet.
Please kindly try version 7.3.0 and tell me if that resolved your problem. If not, I'm going to need a minimal reproduction in CodeSandbox or something similar to help you out.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
