### ISSUE TITLE
Need onOpen function

### ISSUE THREAD

**Issue by vanmanh49** [wojtekmaj/react-date-picker#140]
How to know when the Calendar isOpen or not!

**Comment by wojtekmaj** [comment]
Calendar opens when a field inside React-Date-Picker is focused, and closes whenever `mousedown` or `focusin` happens outside React-Date-Picker's container.

You can access React-Date-Picker's state, but I think it would make sense to add these callbacks :)

**Comment by wojtekmaj** [comment]
`onCalendarOpen` and `onCalendarClose` will be added in the next release!

**Comment by vanmanh49** [comment]
Thank you. Hope these callbacks come soon! 🙂

**Comment by wojtekmaj** [comment]
I'm digging myself out of notifications, so it will take a while to verify if there's nothing stopping me from releasing a new version (like a critical bug that has to be fixed in current version range), but other than that we're ready to release :)

Apologies for the wait.
