### ISSUE TITLE
Write Custom words in the field

### ISSUE THREAD

**Issue by nagy3n** [wojtekmaj/react-date-picker#144]
this what happened when i tried to write week day name beside the date using format props
![image](https://user-images.githubusercontent.com/11620728/55414521-8ef82700-556b-11e9-8a17-59b233dc4785.png)

**Comment by wojtekmaj** [comment]
Good. You're not supposed to do this.

T, e are not in ISO standard. u, s, a are tokens not supported by React-Date-Picker. `date-fns` would behave similarly:

```js
var dateFns = require("date-fns");
dateFns.format(new Date(), 'Tuesday'); // "Tue33pmy"
```

**Comment by nagy3n** [comment]
Dude how about adding a propriety to add whatever i want to the field without causing problems.

Thanks.

**Comment by nagy3n** [comment]
> Good. You're not supposed to do this.
> 
> T, e are not in ISO standard. u, s, a are tokens not supported by React-Date-Picker. `date-fns` would behave similarly:
> 
> ```js
> var dateFns = require("date-fns");
> dateFns.format(new Date(), 'Tuesday'); // "Tue33pmy"
> ```

Dude how about adding a propriety to add whatever i want to the field without causing problems.

Thanks.
