### ISSUE TITLE
Adding custom text to field

### ISSUE THREAD

**Issue by nagy3n** [wojtekmaj/react-date-picker#145]
Can you add a propriety to add whatever string i want to the field without causing problems aside of format.
Or give me push permission.
Thanks.

**Comment by wojtekmaj** [comment]
Hi,
React-Date-Picker is open sourced, so if you need something unusual you can always fork it and add whatever you need :)
React-Date-Picker is trying to match native date pickers as closely as possibly, and as such custom content won't be supported on this, main, branch.
