### ISSUE TITLE
All <input> fields get 0px width after switching between tabs

### ISSUE THREAD

**Issue by xlr8tn** [wojtekmaj/react-date-picker#146]
I currently have 2 date range pickers on a tab that have default values set.  If I switch to a second tab and then back to the first tab, my dates are all messed up.  I traced it down to the utils call that sets width mistakenly to 0px.  This causes my date to be displayed like 1/3/20 instead of 10/30/2018 because of the 0 width inputs.  Initially, these values are either 8px, 16px, or 32px depending on day, month, or year settings.  It seems like a render issue because if I re-click the first tab, the date pickers look perfect again.

**Comment by nguyenquyhy** [comment]
I have the same issue of all the width is set to 0 initially. The width changes back to correct value once I click on the picker.

**Comment by wojtekmaj** [comment]
Do you think you could provide a Code Sandbox for me to reproduce this?

**Comment by wojtekmaj** [comment]
Fixed; now we're using canvas measureText technique to measure text length, which makes it immune to issues caused by invisible elements, and is much faster on Firefox.

Next release of React-Date-Picker will have the fix applied.
