### ISSUE TITLE
DD/MM/YYYY Placeholder instead of --/--/----

### ISSUE THREAD

**Issue by Lipfroy** [wojtekmaj/react-date-picker#147]
I was requested to provide more clear representation of date formatting for punch in dates.
Could you please point to file where placeholder is set. Thanks

**Comment by wojtekmaj** [comment]
But there's no placeholder in React-Calendar 🤔 Maybe you mean React-Date-Picker or something similar?

**Comment by wojtekmaj** [comment]
Duplicate of #6
