### ISSUE TITLE
after npm link react-datepicker module not found

### ISSUE THREAD

**Issue by MoAli2016** [wojtekmaj/react-date-picker#149]
while playing with react-datepicker, I created two folders, one is react-datepicker I did `sudo npm link`. On the prj folder, I did `npm link react-datepicker,` I can see the module installed in node_modules, but when I run prj I get
_ERROR in ./src/containers/Home/Search/DateTimePicker.js
Module not found: Error: Can't resolve 'react-datepicker' in '/Users/.../src/containers/Home/Search.js
I am referencing the component in the search.js. I am using React 16 and webpack 4.
On the other hand if I do `npm install` and pull react-datepicker from npm prj works fine. If I were to make changes to the component src code, how can I get it to run locally without errors. Any ideas

**Comment by wojtekmaj** [comment]
Sounds like NPM issue to me, consider https://npm.community/ to get help with NPM.

**Comment by MoAli2016** [comment]
ok thanks I will

**Comment by wojtekmaj** [comment]
BTW looking at this shouldn't it be `npm link react-date-picker`? Maybe you just mistyped the name?
