### ISSUE TITLE
Position issue when container position: sticky

### ISSUE THREAD

**Issue by wwitekk** [wojtekmaj/react-date-picker#150]
Hi,

I am using "react-date-picker": "7.5.0" with "react": "16.8.4",, insight a container that has position: sticky set in css. On mobile, when you scroll page to the bottom (more than the calendar popup height) it will display the calendar above the '.react-date-picker__wrapper' (instead of below) element and at the same time above currently visible area.

CSS for the container element is: 
```
    display: flex;
    position: sticky;
    margin-top: 10px;
    top: 0;
    justify-content: space-between;
    padding: 20px 0;
```

Regards

Witold

**Comment by n1cklarosa** [comment]
I too have this issue..
