### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.target')

### ISSUE THREAD

**Issue by fusengine** [wojtekmaj/react-date-picker#153]
TypeError: null is not an object (evaluating 'e.target')

```
const [ formData, setFormData ] = useState({
		company: '',
		title: '',
		location: '',
		from: '',
		to: '',
		current: false,
		description: ''
	})
	const [ toDateDisabled, toggleDisable ] = useState(false)

	const { company, title, location, from, to, current, description } = formData
	const onChange = (e) => setFormData({ ...formData, [e.target.name]: e.target.value })
```

`<DatePicker
	name="from"
	value={from}
	onChange={(e) => onChange(e)}
	className="form-control"
/>
`

<img width="1084" alt="Capture d’écran 2019-05-12 à 22 32 38" src="https://user-images.githubusercontent.com/7295655/57587501-e2b04580-7505-11e9-9264-716b314b340d.png">

why this don't work??

**Comment by wojtekmaj** [comment]
As per documentation, onChange returns a value, not an event. The reason for this is that React-Date-Picker contains multiple form elements that work together to build one input, behaving as close to native date picker as possible.

So instead of:

```js
<DatePicker
  name="x"
  onChange={event => this.setState({ [event.target.name]: event.target.value })}
/>
```

consider:

```js
const name = x;
// ...
<DatePicker
  name={name}
  onChange={value => this.setState({ [name]: value })}
/>
```
