### ISSUE TITLE
Uncaught Invariant Violation: Input(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by AshvinkumarPatel** [wojtekmaj/react-date-picker#154]
I am using react: ^15.1.0
While using date picker it gives me above error.

Can anyone help me on that?

**Comment by wojtekmaj** [comment]
Hey there,
as README states minimum version supported is 15.5, and this only for some of the older versions. The newest versions are compatible with React 16.0 and up. I'm sorry to say that there are no plans to support older versions (in fact, the opposite will happen and we'll probably require newer versions of React to take advantage of React Hooks and some other architectural improvements).

React 15.0 is almost two years old, it's slow, full of bugs, vulnerabilities and is very limiting to the developers. I highly suggest doing an upgrade!
