### ISSUE TITLE
The calendar should be on top of other component

### ISSUE THREAD

**Issue by thomaslc66** [wojtekmaj/react-date-picker#155]
When displaying the calendar to select the date, the calendar should be on top of other components, not behind.

Here i can only see the first row of the calendar

![image](https://user-images.githubusercontent.com/9827392/57693418-6e7eba80-7649-11e9-9659-cf9ab1a250a9.png)

Firefox: 66.0.5

**Comment by wojtekmaj** [comment]
Hi,
there's no way for me to include styles that works for everyone. Some people will like the calendar to be covered by something, others not. You will need to modify the CSS in order to achieve what you want.
