### ISSUE TITLE
How to automatically focus input on mount?

### ISSUE THREAD

**Issue by sanfer94** [wojtekmaj/react-date-picker#167]
How do you automatically focus this component when the page loads? There doesn't seem to be any way according to the props the component displays

**Comment by wojtekmaj** [comment]
Hi,
please remember that automatically focusing inputs is generally discouraged as it creates accessibility issues.

Should you prefer to proceed anyway, I'm afraid you'd need to do it on your own by writing something along the lines:

```js
document.querySelector('.react-date-picker input:not([type="date"])').focus();
```
