### ISSUE TITLE
Remove icon outline on hover or focus?

### ISSUE THREAD

**Issue by fahadAziz44** [wojtekmaj/react-date-picker#169]
I have provided my own icon for calendar using calendarIcon prop. But when we hover or focus it, an outline appears (colored: rgb(0, 120, 215)).
How can we remove that outline?

**Comment by wojtekmaj** [comment]
`.react-date-picker__button svg g` is the selector we add `stroke` to by default styling. You can overwrite it. But since this style was written before anyone could use their own SVGs for calendar icons, I'll consider these styles added to 3rd party icons as a bug.
