### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by third774** [wojtekmaj/react-date-picker#17]
Would be great to have TypeScript definitions included with the module. I might try to work on a PR for this, but figured I should open the issue in case someone wants to jump on it before I get around to it.

**Comment by wojtekmaj** [comment]
Hey @third774! I think it's an excellent idea. I don't have any experience in TypeScript though, so I'm not confident doing this right away, especially on this project which has around 60,000 downloads/mo. I do releases very carefully... ;)

**Comment by third774** [comment]
PR https://github.com/wojtekmaj/react-date-picker/pull/18 created! 🕺
