### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by FagerKod** [wojtekmaj/react-date-picker#170]
Seems the class `react-date-picker__calendar react-date-picker__calendar--open` gets inline styles even though I import `import DatePicker from 'react-date-picker/dist/entry.nostyle';`.

Used on this calendar:

https://www.1177.se/Stockholm/barn--gravid/graviditet/graviditeten-vecka-for-vecka/graviditetskalendern/

**Comment by wojtekmaj** [comment]
Hi,
yes, this is by design. Calendar position on the screen is calculated dynamically, so there's no really a way around it than using inline style to position it well.
