### ISSUE TITLE
removing the initial border

### ISSUE THREAD

**Issue by radjivF** [wojtekmaj/react-date-picker#171]
Hi I cant figure out how to remove this border, any help?

![image](https://user-images.githubusercontent.com/5714138/60796686-74ec6700-a1a0-11e9-8e8c-1748bfa80628.png)

![image](https://user-images.githubusercontent.com/5714138/60797326-a3b70d00-a1a1-11e9-94ce-8eb8518e99ec.png)

**Comment by wojtekmaj** [comment]
Hi,
you can remove it by writing your own CSS, or by using `entry.nostyle` (more on that in README) and replacing the default CSS with your own, edited ones.

**Comment by JSmith989** [comment]
this solution is what worked for me 

    .react-date-picker .react-date-picker__wrapper {
      border: none;
      box-shadow: none;
    }
