### ISSUE TITLE
Add the ability to track the event of the occurrence of an incorrect date format.

### ISSUE THREAD

**Issue by LeonidYarosh** [wojtekmaj/react-date-picker#173]
I would like to be able to block other form elements if the date is entered incorrectly. To do this, I would like to have an error handler, or at least an input in the text field (onError and onInput). It may also be more convenient to set the input format hard.

Thanks.
Leonid

**Comment by wojtekmaj** [comment]
Hi, while React-Date-Picker does not accept onInvalid callback, it does not stop it from bubbling in any way. That being said, you can do something like this:

https://codesandbox.io/s/react-date-picker-oninvalid-pe47t

Of course, you could optimize it by e.g. not setting `isInvalid` flag to `true` every time an input is made only to set it back to `false` sometimes, but that's only for illustration purposes.

Hope this helps!
