### ISSUE TITLE
Add support for `readonly` prop

### ISSUE THREAD

**Issue by supersnager** [wojtekmaj/react-date-picker#174]
Hi,
how can i set readonly attribute to date input?

**Comment by wojtekmaj** [comment]
You can't - and it's a silly overlook, it would be a nice addition! :+1:

**Comment by wojtekmaj** [comment]
This is in the works.

**Comment by wojtekmaj** [comment]
Issue: Some elements like MonthSelect can't be `readonly` because `select` doesn't support `readonly`. We need hidden inputs that represent these values when `select` elements are disabled.

**Comment by rscotten** [comment]
@wojtekmaj So, it appears there's intentionally no `readOnly` prop?  Is there another preferred way for disabling the mobile keyboard?

**Comment by wojtekmaj** [comment]
Well I wouldn't call that intentional, I would very much like that to be implemented but the issue described above makes it difficult.

I'd suggest just using disabled prop instead, or play with CSS user-select.

**Comment by rscotten** [comment]
@wojtekmaj I couldn't get CSS `user-select: none` to work.  

So you're saying it's too difficult to pass a `readOnly` prop down into those three input elements?

For anybody else facing this problem, here's my minimized brute force solution:

```typescript
export const SingleDayPicker = ({ name }) => {

  useEffect(() => {
    if (!isMobileDevice()) return;

    const element = document.querySelector(`input[name=${name}]`);

    if (!element) return;

    const elements = element.parentElement?.getElementsByClassName(
      'react-date-picker__inputGroup__input'
    );

    if (elements?.length === 3) {
      elements.item(0)?.setAttribute('readonly', 'readonly');
      elements.item(1)?.setAttribute('readonly', 'readonly');
      elements.item(2)?.setAttribute('readonly', 'readonly');
    }
  }, []);

  return (
    <DatePicker name={name} />
  );
};
```

**Comment by abaksha-sc** [comment]
Was `readOnly` support removed? I can't found it in current version (10.2.0)
