### ISSUE TITLE
How to style the date picker?

### ISSUE THREAD

**Issue by austinrchow** [wojtekmaj/react-date-picker#177]
new to react and unsure exactly how to style the Datepicker. Currently just using className when initializing the datepicker to change font family and size. However how do you style more specific things, like hover color etc.  Are there examples of general styling?

**Comment by wojtekmaj** [comment]
Hey,
you can look in [the source for original LESS file](https://github.com/wojtekmaj/react-date-picker/blob/master/src/DatePicker.less) to see how it was styled. Based on this, you can create your own set of styles! Good luck!
