### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by sdelvalle57** [wojtekmaj/react-date-picker#178]
node_modules/react-calendar/dist/Calendar.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .react-calendar {
|   width: 350px;
|   max-width: 100%;

**Comment by wojtekmaj** [comment]
Your Webpack config (or any other bundler you're using) has to be properly configured for CSS files.

**Comment by SasSam** [comment]
Default Next.js setup throws error as well:
![image](https://user-images.githubusercontent.com/496429/148446907-339c558a-b1b0-4a1b-b627-76b1cdbdd710.png)

The linked page about the issue: https://nextjs.org/docs/messages/css-npm

It says:

> **CSS Imported by a Dependency**
> **Why This Error Occurred**
> One of your dependencies (node_modules) imports a CSS file.
> 
> This normally happens when a package's source files are accidentally consumed, instead of the built package.
> 
> **Possible Ways to Fix It**
> 
> Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
> Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.
> The dependency should also provide instructions about what CSS needs to be imported by you, in your application.
> Importing CSS files within node_modules cannot be supported because we cannot know the correct behaviour:
>     - Should the file be consumed as Global CSS or CSS Modules?
>     - If Global, in what order does the file need to be injected?
>     - If Modules, what are the emitted class names? As-is, camel-case, snake case?
>     - Etc...

Any suggestions?

**Comment by klichg0ky** [comment]
> Default Next.js setup throws error as well: ![image](https://user-images.githubusercontent.com/496429/148446907-339c558a-b1b0-4a1b-b627-76b1cdbdd710.png)
> 
> The linked page about the issue: https://nextjs.org/docs/messages/css-npm
> 
> It says:
> 
> > **CSS Imported by a Dependency**
> > **Why This Error Occurred**
> > One of your dependencies (node_modules) imports a CSS file.
> > This normally happens when a package's source files are accidentally consumed, instead of the built package.
> > **Possible Ways to Fix It**
> > Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
> > Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.
> > The dependency should also provide instructions about what CSS needs to be imported by you, in your application.
> > Importing CSS files within node_modules cannot be supported because we cannot know the correct behaviour:
> > - Should the file be consumed as Global CSS or CSS Modules?
> > - If Global, in what order does the file need to be injected?
> > - If Modules, what are the emitted class names? As-is, camel-case, snake case?
> > - Etc...
> 
> Any suggestions?

i fixed it with this line
`
import DatePicker from "react-date-picker/dist/entry.nostyle";`
and then added this lines in global css file

```
@import "react-date-picker/dist/DatePicker.css";
@import "react-calendar/dist/Calendar.css";
```
