### ISSUE TITLE
Clear button shows 1969-12-31

### ISSUE THREAD

**Issue by JoseGeorges8** [wojtekmaj/react-date-picker#179]
When I click the clear button, 1969-12-31 gets populated on the datepicker...

**Comment by wojtekmaj** [comment]
Sounds like you have a default set somewhere. Mind sharing your implementation?

**Comment by JoseGeorges8** [comment]
Sorry for the late response!

Here is how I implemented it 

```js
<DatePicker
    clearIcon={null}
    className={classes.datePicker}
    format="y/MM/dd"
    onChange={this.handleDateChange('from_date')}
    value={this.state.display_from_date}
/>
<p className={classes.formLabel}>To</p>
```

I took the clear icon out just because of the issue

**Comment by JoseGeorges8** [comment]
```js
    handleDateChange = name => event => {
        let d = new Date(event), month = '' + (d.getMonth() + 1), day = '' + d.getDate(), year = d.getFullYear();
        if (month.length < 2) month = '0' + month;
        if (day.length < 2) day = '0' + day;
        console.log([year, month, day].join('/'));
        if(name === 'from_date')
            this.setState({'from_date': [year, month, day].join('/'), 'display_from_date': d});
        else
            this.setState({'to_date': [year, month, day].join('/'), 'display_to_date': d});
    };
```


this is the handle date change method. Thought it'll be worth showing as well!

**Comment by wojtekmaj** [comment]
handleDateChange is actually your problem. an argument, mistakenly called `event` (it's a `date`) is `null` if you clear the picker. You don't check for that, and create a date out of it anyway. `new Date(null)` returns `Jan 01 1970` and there's your problem.
