### ISSUE TITLE
Can't pick date on Safari 12

### ISSUE THREAD

**Issue by IlyaZha** [wojtekmaj/react-date-picker#180]
Can't pick date on Safari 12.1 (latest). https://drive.google.com/file/d/1fFCQdUeaH0uGbY9miXJQC4ONwY3pfx6x/view
Works perfectly on Chrome, but I want my app to work with both browsers.

**Comment by wojtekmaj** [comment]
Hi,
anything in the console? Can you share a part of your implementation? I was testing [our home page](http://projects.wojtekmaj.pl/react-date-picker/) on Safari, both desktop and mobile, and it works just fine.

**Comment by IlyaZha** [comment]
nothing in console...
Yeah, your homepage works fine in Safari 12.1.
I have this code 

```
                 onChange={value => {
                    if (value) {
                      value = moment(value).format(C.INNER_DATE_FORMAT)
                    }
                    this.props.onChange(value);
                  }}
```
May be date couldn't be picked because of this `moment(value)`
