### ISSUE TITLE
Uncaught TypeError: (0 , _utils.updateInputWidth) is not a function [DayInput]

### ISSUE THREAD

**Issue by vadymkukhtinOD** [wojtekmaj/react-date-picker#184]
I am using latest version of react-date-picker within create-react-app typescript app.

I have a very strange issue. when I am rendering component inside another Functional component:

`
DayInput.js:187 Uncaught TypeError: (0 , _utils.updateInputWidth) is not a function
    at ref (DayInput.js:187)
`

but when the component is rendered using storybook without any problems

**Comment by wojtekmaj** [comment]
Which React-Date-Picker version are you using?

**Comment by vadymkukhtinOD** [comment]
Latest one

**Comment by wojtekmaj** [comment]
I'm fairly sure that's not the case. The code the error quotes is gone since v7.6.0.

**Comment by vadymkukhtinOD** [comment]
Unfortunately, that is the case for me and it happens to me on the latest version. I am using Typescript 3.5.2 with the latest create-react-app. If I would have time I will try to show in the sandbox, but for now issue is still there, but unless I won't be able to prove it, this issue can be closed. Thank you
