### ISSUE TITLE
Keyboard input not correct with leading zero

### ISSUE THREAD

**Issue by gardengardengarden** [wojtekmaj/react-date-picker#185]
When i try to enter some date with leading zero, the result is not correct.
For example: 
Testing with chrome (In MM/dd/yyyy format):
When press "01012019", the result become "010/12/019". What I expect is "01/01/2019". 

Testing with Edge (In yyyy-MM-dd format):
Press "2019(right key)0101", result is 2019-010-01.

By the way, when i type 0020190 in the year part, it will become blank page with error in console.
Only occur in Edge, not sure why.

You can try with the demo page:
http://projects.wojtekmaj.pl/react-date-picker/

I found you had already answered another issue which may be related to this?
https://github.com/wojtekmaj/react-date-picker/issues/156#issuecomment-515692395

Anyway, thanks for the work. It saved me from so many headache when facing the native html input type="date".

**Comment by KennethJoris** [comment]
Any news on this bug?

**Comment by antoniojmartnez** [comment]
Hi,

I expose a possible solution to the extra zero problem when showLeadingZeros is being used and a zero is entered first.  ( PR #241   ).

Regards

**Comment by wojtekmaj** [comment]
This will be fixed, but it needs https://github.com/wojtekmaj/react-date-picker/pull/272 to be merged first. For now, we rely on number inputs (from today's point of view I think that was a mistake), which don't report leading zeros in values, so we're technically unaware of them.

**Comment by Liel208** [comment]
Hey, any updates on when this is going to get deployed?
![image](https://user-images.githubusercontent.com/24766104/88483380-12fbcc80-cf70-11ea-97e1-9de8a6abf16b.png)

:(

**Comment by sirsaula** [comment]
Any update on this bug or a workaround @wojtekmaj  ?

**Comment by wojtekmaj** [comment]
#272 is not merged yet because it's missing required input validation. I don't have a lot of free time these days. Sorry!

**Comment by MihaelaTIMIS** [comment]
any updates @wojtekmaj ?

**Comment by arehman97** [comment]
@MihaelaTIMIS Well this worked for me format="M/d/y". Now it takes only a single zero.

**Comment by elemeNtk0** [comment]
We solved the problem on our project by explicitly passing the date format: `format='d.M.yyyy'`

**Comment by wojtekmaj** [comment]
Fixed in v8.1.0.
