### ISSUE TITLE
DatePicker is an empty object

### ISSUE THREAD

**Issue by bogdancaspar** [wojtekmaj/react-date-picker#186]
Hi guys,

I'm trying to use this library but when I do ```import DatePicker from 'react-date-picker'```, DatePicker is an empty object. Did anyone encounter this problem?

I have React 16.8 if it matters.

**Comment by wojtekmaj** [comment]
I think more than React version it matters what is your build config. Are you using Webpack, Parcel, something else?

**Comment by bogdancaspar** [comment]
Webpack 4.39.2.

After some digging, I found that the problem is the fact that the files names are not lower case and somehow, i don't know why, if you write require('./DatePicker') it will be transformed in require('./datepicker'), and since there is no file with this name, I get an empty object.
I have to mention that I've tried all the node version (9, 10, 11, 12) and the problem still persist. Maybe it's something specific to my OS. It's really weird.
