### ISSUE TITLE
Add maxLength prop to inputs

### ISSUE THREAD

**Issue by carlosriveros** [wojtekmaj/react-date-picker#187]
Currently, even if the format is  'M/d/yyy' you can enter any length input for month, day, or year.

![image](https://user-images.githubusercontent.com/1332862/63388473-2a990100-c36e-11e9-8715-9aab1d386872.png)

I have tried using JavaScript to limit the amount of character that can be entered as input, but it does not work.

`    
      document.querySelectorAll('.react-date-picker__inputGroup__year').forEach(el => {
        el.setAttribute('maxlength', 4)
        el.setAttribute('max', 9999)
     })
`

Is there a suggested way to do this?

Otherwise, can we add this feature?

**Comment by carlosriveros** [comment]
unfortunately number type inputs don't accept the maxlength property.
The fix will have to be something like https://stackoverflow.com/questions/9841363/how-to-restrict-number-of-characters-that-can-be-entered-in-html5-number-input-f

**Comment by wojtekmaj** [comment]
`max` is actually already set, but this is only for input validation. Max length is a good idea; native picker has this.

**Comment by karthibalu98** [comment]
I am able to type more than 4 digit even after adding el.setAttribute('maxlength', 4). 
Can you please help me to resolve the same.

**Comment by wojtekmaj** [comment]
With 0f2923a it will no longer be possible to enter values that are longer than max. So, by default, you should be able to enter e.g. year as long as 6 digits (Sep 13 275760 is maximum allowable date in JavaScript), but setting maxDate to something lower than that, e.g. `new Date(9999, 12, 31)` will disable users from writing more than 4 digits in year input.
