### ISSUE TITLE
Get rid of input field altogether

### ISSUE THREAD

**Issue by pashpashpash** [wojtekmaj/react-date-picker#191]
I currently have my own input fields and I'd like to use the react-date-picker lib as a way of just selecting a date-time and fill my existing input with the data. Is this possible currently? The docs don't provide this kind of info

**Comment by wojtekmaj** [comment]
Hmmmmm, so you would just like to have the calendar then? If so, [React-Calendar](https://github.com/wojtekmaj/react-calendar) is what you're looking for.
