### ISSUE TITLE
Updating state variable with the selected date in react-date-picker

### ISSUE THREAD

**Issue by Deval-Jain** [wojtekmaj/react-date-picker#194]
I am new to react and am trying to implement a leave page.
On the page the user will see his existing leaves in a table (in date-picker component). 
He can then update existing leave by selecting a new date in date-picker component.

In the state variable, I bring all the leaves (for this user) from the API and keep in page (in array)
I iterate through this array and display the leaves using the date-picker.
Now if the user selects a new date, I am trying to pass the array index along with newly selected date in onChange method. I want to update the existing array in state at the passed index with the selected value.

But onChange is unable to accept 2 arguments so I guess this strategy wont work. Can you please suggest an alternative strategy.

I am not using redux, just reactjs.

**Comment by wojtekmaj** [comment]
One strategy would be to create a [curried](https://dev.to/bettercodingacademy/functional-programming-all-you-need-to-know-about-currying-5k7) onChange function which gets the index from somewhere else. :)
