### ISSUE TITLE
Add support for a single placeholder for empty input

### ISSUE THREAD

**Issue by abhigk** [wojtekmaj/react-date-picker#195]
Like in input field place "Select your date of birth".

**Comment by wojtekmaj** [comment]
Hi,
this does not work in native HTML5 date inputs and I see no technical possibility of implementing this feature in React-Date-Picker either. Sorry about that!

I encourage you to use `dayPlaceholder`, `monthPlaceholder` and `yearPlaceholder` props instead.

**Comment by wojtekmaj** [comment]
Duplicate of #86
