### ISSUE TITLE
onCalendarClose and onCalendarOpen props missing in props ts interface

### ISSUE THREAD

**Issue by jbojcic1** [wojtekmaj/react-date-picker#197]
onCalendarClose and onCalendarOpen props are missing in .d.ts file

**Comment by wojtekmaj** [comment]
It would be great to move the types to definitely-typed. I don't have the tools or experience to maintain and test typings.

**Comment by jbojcic1** [comment]
I see. Do you think it's worth adding these two to the interface as a quick win? I could do a PR

**Comment by wojtekmaj** [comment]
Sure thing, at least the typings will be in a better state before we move them to definitely-typed.
