### ISSUE TITLE
Need help for disabling weekends

### ISSUE THREAD

**Issue by MedhaSingh32** [wojtekmaj/react-date-picker#198]
Hi,
I wanted to disable weekends in my calendar. Can you tell which specific attribute can be used?

**Comment by wojtekmaj** [comment]
You can use `tileDisabled` prop to disable the dates in the calendar ([more on that in React-Calendar's README](https://github.com/wojtekmaj/react-calendar)) but you can't disable selective dates in React-Date-Picker itself. It's not possible in native picker either. Sorry about that.
