### ISSUE TITLE
Highlight specific day.

### ISSUE THREAD

**Issue by ajoshi123** [wojtekmaj/react-date-picker#20]
I want to implement a holiday list and change the style for the same day in calendar. 
Any way to highlight a specific day like **Holiday or Holiday list**?

**Comment by wojtekmaj** [comment]
Hmmmm, you can certainly add some content to any day/month/year/decade tile, but it's not currently possible to apply styles based on it.

As a workaround, you could use renderChildren for rendering custom content for these tiles and style it with CSS.

I do think that would be an awesome thing to have. There could be two approaches:

- Passing a list of holidays
- Passing a function that, given date, returns the list of custom classes for each tile

I need to think what would be better. The latter, I think...

**Comment by wojtekmaj** [comment]
Hey @ajoshi123, good news!
React-Calendar version 2.4.0 just went live. This means that you can use its new functionalities throuh react-date-picker, and that includes custom classNames based on dates! Check out `tileClassName` (and `tileContent`) in README.md.
Hope this helps!

PS. Update react-date-picker to 6.3.2 if you're a TypeScript user. You're fine with 6.3.1 if you're using plain JavaScript.
