### ISSUE TITLE
Calendar should open at top or bottom depending on availability of space

### ISSUE THREAD

**Issue by gnigam** [wojtekmaj/react-date-picker#200]
<img width="1436" alt="Screenshot 2019-10-07 at 4 07 38 PM" src="https://user-images.githubusercontent.com/13609777/66305330-bd8cfb00-e91c-11e9-8319-2aa3366d81f3.png">

Datepicker calendar should dynamically choose the direction depending on the availability of space. Right now, it is always opening at the top of the input field even if there is no space available. Attached screenshot from demo page at URL: http://projects.wojtekmaj.pl/react-date-picker/

**Comment by bijay-ps** [comment]
did anyone find any fix or workaround for this issue??

**Comment by astrot1988** [comment]
Something wrong with react-fit component. Same issue

**Comment by FranciscoMCG** [comment]
Same issue here. I've found a few threads with people asking for this. but no useful feedback so far. @wojtekmaj ?
