### ISSUE TITLE
How to change first day of week?

### ISSUE THREAD

**Issue by jpavelw** [wojtekmaj/react-date-picker#205]
It currently shows Monday as the first day and I'd like to set it o Sunday

![Capture](https://user-images.githubusercontent.com/10341134/68900841-1a918300-070b-11ea-9226-23bbdde40188.PNG)

**Comment by wojtekmaj** [comment]
Use `locale` prop :) Every locale has a proper (hopefully!) calendar configured.

**Comment by maxpayneatlarge** [comment]
Setting calendarType="US" also resolves this.

**Comment by wojtekmaj** [comment]
Indeed, you can force calendar type using calendarType prop; otherwise it will be deducted from locale. Thanks for mentioning that!
