### ISSUE TITLE
Compatability with react-calendar 3.0

### ISSUE THREAD

**Issue by bobrobcpp** [wojtekmaj/react-date-picker#206]
I'm using v3.0.0-beta of react-calendar which builds nested esm and umd folders within the dist folder, so these modules are currently not being found by react-date-picker.  
Any workaround?

**Comment by wojtekmaj** [comment]
Once React-Calendar 3.0.0 goes out of beta (I'm waiting for any feedback, if there's no bugs I'll just release it), React-Date-Picker will get the update on the same day.

If you want to test it out, you may use [Yarn's selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force React-Calendar 3.0-beta to be used. I didn't test it, but should be fine.
