### ISSUE TITLE
Calendar closes on drilldown from century to decade, decade to year and year to month

### ISSUE THREAD

**Issue by joebourne** [wojtekmaj/react-date-picker#21]
When you drilldown from any view except top level (click a month name to get to month view / click a year to get to year view / click a decade to get to decade view), the calendar closes.

The blur method changed in PR https://github.com/wojtekmaj/react-date-picker/pull/19 and this may be a side effect.

I am trying to fix it but wonder if you might have any advice. It seems that the `event.target` of the click registers as being outside of the date-picker when clicking on a month, year or decade to drill down.

Therefore `!this.wrapper.contains(event.target)` (in the `onClick` function of DatePicker.jsx) is evaluating to true and `this.closeCalendar()` is being called.

Could it be something to do with the click handling in the wojtekmaj/react-calendar library that doesn't work with the new blur method?

Thanks for your help.

**Comment by wojtekmaj** [comment]
Hmm. I'll have a look on it in a couple of hours.

**Comment by joebourne** [comment]
@wojtekmaj I think it's fixed in my latest PR https://github.com/wojtekmaj/react-date-picker/pull/22. Please check and let me know.

**Comment by wojtekmaj** [comment]
Well, actually again it must have been macOS-only issue, so I must trust you on this! Sorry for messing that up!
