### ISSUE TITLE
Unable to stop typing more than 4 digit in year textbox.

### ISSUE THREAD

**Issue by karthibalu98** [wojtekmaj/react-date-picker#212]
I have added below code in my project, but still I am able to type more than 4 digit.
document.querySelectorAll('.react-date-picker__inputGroup__year')
            .forEach(el => { el.setAttribute('maxlength', 4); el.setAttribute('max', 9999) })

Can any one help to resolve this issue. it's bit urgent.

**Comment by wojtekmaj** [comment]
You can't apply maxLength attribute to number inputs. Lack of maxLength here is by design, too - year e.g. 10392 is perfectly valid.

If you need to apply maxLength, I suggest:

```js
function onKeyPress(event) {
  const selection = window.getSelection().toString();

  // If the user selected any text, pressing the next key will not cause maximum length to be passed
  if (selection) {
    return true;
  }

  const nextValue = event.target.value;
  const maxLength = 4;

  if (nextValue.length >= maxLength) {
    event.preventDefault();
    return false;
  }

  return true;
}
```

**Comment by karthibalu98** [comment]
@wojtekmaj Thank you so much. 
It is working for me

**Comment by wojtekmaj** [comment]
With 0f2923a it will no longer be possible to enter values that are longer than max. So, by default, you should be able to enter e.g. year as long as 6 digits (Sep 13 275760 is maximum allowable date in JavaScript), but setting maxDate to something lower than that, e.g. `new Date(9999, 12, 31)` will disable users from writing more than 4 digits in year input.
