### ISSUE TITLE
Chrome (still) doesn't respect autocomplete="off"

### ISSUE THREAD

**Issue by UlyssesInvictus** [wojtekmaj/react-date-picker#214]
This was previously addressed in https://github.com/wojtekmaj/react-date-picker/issues/129, but sadly Chrome seems to ignore it...

However, this SO answer suggests you can just set the autocomplete value to gibberish, which works, so is it possible to change it so they match that? (I can write the PR if necessary.)

https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off

**Comment by wojtekmaj** [comment]
Looks like we would like
```
autoComplete={name}
```
instead of
```
autoComplete="off"
```
in Input.jsx, right?

I only wonder how this would affect other browsers. I'm not gonna change something that fixes Chrome and breaks things on different browsers.

**Comment by UlyssesInvictus** [comment]
Good point -- I can look into it on different browsers and report back.

It's not a crucial change, so I would understand if you wanted to just
close the issue.
