### ISSUE TITLE
getFontShorthand is not a function 

### ISSUE THREAD

**Issue by sachinkotwal** [wojtekmaj/react-date-picker#220]
I am getting below issue after using this date picker component 
index.es.js:7783 Uncaught TypeError: (0 , i.getFontShorthand) is not a function. Not sure what is causing this issue.
I created wrapper in my component library project to export this component. I am using rollup to build my library project initially I suspected that this could be the issue of minification. But didn't find any solution

**Comment by aharris** [comment]
I have been trying to debug this one for a while now to no avail. The closest I can see so far is a versioning issue. The only difference i see is in my `package.lock`. Even though i use exact versions this does not. In an  older working version I have:

```
react-date-picker@7.8.1, react-date-picker@^7.8.0:
  version "7.8.1"
  resolved "https://npm.ey-intuitive.com:443/react-date-picker/-/react-date-picker-7.8.1.tgz#9dac7af457596649e97a664dfd6b38826b314a0d"
  integrity sha512-mwWfhtj1aqTObg8ZwGqc5J58JjqVJzNqoLs30fOSgTjinebPGHaNeGUTd2vlDjMFN+bTwP/WLl1jwCDCTlMguw==
  dependencies:
    get-user-locale "^1.1.1"
    make-event-props "^1.1.0"
    merge-class-names "^1.1.1"
    prop-types "^15.6.0"
    react-calendar "^2.18.0"
    react-fit "^1.0.3"
    react-lifecycles-compat "^3.0.4"
    update-input-width "^1.1.0"
```

In the broken version where i get this error I have 2 versions:

```
react-date-picker@7.8.1:
  version "7.8.1"
  resolved "https://npm.ey-intuitive.com:443/react-date-picker/-/react-date-picker-7.8.1.tgz#9dac7af457596649e97a664dfd6b38826b314a0d"
  integrity sha512-mwWfhtj1aqTObg8ZwGqc5J58JjqVJzNqoLs30fOSgTjinebPGHaNeGUTd2vlDjMFN+bTwP/WLl1jwCDCTlMguw==
  dependencies:
    get-user-locale "^1.1.1"
    make-event-props "^1.1.0"
    merge-class-names "^1.1.1"
    prop-types "^15.6.0"
    react-calendar "^2.18.0"
    react-fit "^1.0.3"
    react-lifecycles-compat "^3.0.4"
    update-input-width "^1.1.0"

react-date-picker@^7.8.0:
  version "7.10.0"
  resolved "https://npm.ey-intuitive.com:443/react-date-picker/-/react-date-picker-7.10.0.tgz#890f37684da5087c80d63132b4e77e3d0677b332"
  integrity sha512-5lyWOeSMeCmzqKTd5X1W2jaxPU67Pu06IMmjKmh/tgw0u6QM2UHkwmBlZnMoBuaxrjMlc33HrssxB4EkUyqzHg==
  dependencies:
    "@wojtekmaj/date-utils" "^1.0.0"
    get-user-locale "^1.2.0"
    make-event-props "^1.1.0"
    merge-class-names "^1.1.1"
    prop-types "^15.6.0"
    react-calendar "^2.19.1"
    react-fit "^1.0.3"
    react-lifecycles-compat "^3.0.4"
    update-input-width "^1.1.1"
```

I have been unsuccessful at overwriting this new version so far.

**Comment by aharris** [comment]
The issue seems to come from `update-input-width": "1.2.0`.

I added a resolution for `1.1.1` and it is working again. 

```
  "resolutions": {
    "update-input-width": "1.1.1"
  }
```

Looks like this package has been updated behind the scenes. Is it possible to use exact versions so these types of issues can be prevented in the future?

**Comment by kimmoxter** [comment]
> The issue seems to come from `update-input-width": "1.2.0`.
> 
> I added a resolution for `1.1.1` and it is working again.
> 
> ```
>   "resolutions": {
>     "update-input-width": "1.1.1"
>   }
> ```
> 
> Looks like this package has been updated behind the scenes. Is it possible to use exact versions so these types of issues can be prevented in the future?

This is the correct solution, at least for now.. Worked for me.
I've been using this library and because art of magic didn't work anymore haha. 
Thanks.

**Comment by wojtekmaj** [comment]
Hi,
This issue may indeed affect older versions of React-Date-Picker. Sadly I have no capacity to create hotfixes for minor releases. Consider updating to the newest non breaking version!

**Comment by marcolazzarini** [comment]
Hi, 
I tried multiple times (forcing resolution block in package.json, manually changing yarn.lock file) but this problem prevents me from using this component. 
The downloaded version of update-input-width is 1.2.1 (react-date-picker version is 8.0.1), causing the page to break with the reported error:

Uncaught TypeError: (0 , i.getFontShorthand) is not a function 

Is there any chance un update will be released fixing update-input-width version?

**Comment by wojtekmaj** [comment]
v1.2.1 should have getFontShorthand already exposed (it's a feature introduced in update-input-width v1.1.0). Maybe you have multiple versions of update-input-width in your lockfile?
