### ISSUE TITLE
Why version 5.0 series been deprecated?

### ISSUE THREAD

**Issue by naveen-gupta** [wojtekmaj/react-date-picker#224]
Team i was using react-date-picker version 5.3.28 for my application, with react version 15.0.1 .Now this has been deprecated as well as removed from npm registry, So my app is unable to make build. If i  will go with newer version than there is requirement of react version update. Please guide me what I have to do in this case?

**Comment by wojtekmaj** [comment]
> Now this has been deprecated

Correct

> as well as removed from npm registry

Literally impossible

> Why version 5.0 series been deprecated?  

Maintainers of version 5.0 abandoned it completely and because of that, 6.0 (and up) were released to replace it with a maintained package.

> Please guide me what I have to do in this case? 

Well, you could keep using 5.x or upgrade to React 16.
