### ISSUE TITLE
How can I "cancel" a date change?

### ISSUE THREAD

**Issue by tonycassara** [wojtekmaj/react-date-picker#226]
Hi Wojtek!

I love your library! Currently, we're trying to extend our `onChange` method to support an inbetween validation in the form of a modal. The process looks like this:

1. Click "Change ship date".
2. See Calendar drop down.
3. Select a date.
4. If date falls in a certain range.
    1. prompt the user to confirm.
    2. If they select "No", then cancel the date change.
    3. If they select "Yes', continue with the date change.

I can almost get this to work except it seems the `Calendar` component is still changing `this.state.value` to the date that was most recently clicked. See: https://github.com/wojtekmaj/react-calendar/blob/e177d0ac64fbcc14e15c352fc81b4e22544dbd48/src/Calendar.jsx#L310

What would be an appropriate way to cancel this? Currently I'm setting state twice to force an update and set it back. Perhaps I could pass an `onClick` handler that wraps the `onClick` variable in `Calendar.jsx` if present and passes callbacks for `this.onChange` or `this.drillDown`? https://github.com/wojtekmaj/react-calendar/blob/e177d0ac64fbcc14e15c352fc81b4e22544dbd48/src/Calendar.jsx#L380

Happy to open a PR if that seems like an acceptable method!

**Comment by tonycassara** [comment]
Turns out it's a problem with our internal implementation. Woops!

**Comment by tonycassara** [comment]
Reopening because the functionality I want to modify is within `react-calendar`

**Comment by tonycassara** [comment]
Rethinking this a few days later, I think having an `onClickValidation` method might be better, with a default method that just invokes the `onClick` defined in `Calendar.jsx`

**Comment by wojtekmaj** [comment]
React-Calendar 3.0 is a controlled component so "cancelling" date is as easy as not updating it on your side. However, React-Calendar 3.0 is a breaking update and for React-Date-Picker to be controlled as well, we will need a breaking release as well.

**Comment by tonycassara** [comment]
@wojtekmaj thanks for that, well consider moving to 3.0 in the future. I'll close this comment for now.
