### ISSUE TITLE
Positioning of react-date-picker

### ISSUE THREAD

**Issue by bijay-ps** [wojtekmaj/react-date-picker#229]
Hi,

I am using this library and like it for it's simplicity and easy to use features. And now am stuck at one point. Check the image attached [date picker](https://imgur.com/a/UpcagC4) 

As you can see the top part is hidden behind my menu bar.

How can I position it to open somewhere else or modify the css myself to adjust it's position.

I have made a reusable component using this date picker, code is below:

```js
import React from 'react';
import DatePicker from 'react-date-picker';

const CustomDatePicker = ({dtVal, handleChange}) => {
  return (
      <>
        <DatePicker
          onChange={handleChange}
          value={dtVal}
          clearIcon={null}
          format="dd/MM/yyyy"
          className="mr-2"
        />
     </>
  );
};

export default CustomDatePicker;
```

And it is being used like this:

```js
<LabelContainer className="mr-2"> Visited On:</LabelContainer>
<CustomDatePicker 
  calendarClassName="calender-custom-position" 
  className="ml-4" 
  dtVal={visitDate}
  handleChange={onDateChange}
/>
```

**Comment by gabrielgrover** [comment]
I have a similar issue. On mobile devices the date picker collides with our navbar. It would be great if we could control the direction the date picker opens 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sullyslegacy** [comment]
I agree had to add

```css
.react-date-picker__calendar--open {
  top: 100% !important;
  bottom: unset !important;
}
```
so Date Picker always shows under input

**Comment by sukesh-s** [comment]
Hi 
I'm using the version 7.9.0 
I have the issue when i use Date picker on modal like this [image](http://i.imgur.com/i5F0iky.png)

My code is 
```
<div>
<label className="col-form-label-sm">EndDate</label>
              <DatePicker
                onChange={event => onEndDateChange(event )}
                maxDate={EndDate}
                minDate={StartDate}
                value={endDate}
              />
</div>   
```

**Comment by sukesh-s** [comment]
Hi
I'm also having a issue i'm using version 7.9
I'm using date picker on modal [here](http://i.imgur.com/i5F0iky.png)

**Comment by wojtekmaj** [comment]
@sukesh-s Your modal window styling causes calendar to be cut off. Sadly the only thing that could "escape" overflow hidden is position float, which creates so many issues on its own I've decided not to go for it.

**Comment by benesva4** [comment]
Try to give it `position: fixed;`
