### ISSUE TITLE
locale problem

### ISSUE THREAD

**Issue by PetrSnobelt** [wojtekmaj/react-date-picker#23]
Hi, 
when I set locale to "cs-CZ" input display only day number and nothing else.

When I use "de-DE" which has the same display format "dd.MM.yyyy" it displays value in input correctly.

Any idea?

**Comment by PetrSnobelt** [comment]
I found out that problem is caused by placeholder (https://github.com/wojtekmaj/react-date-picker/blob/master/src/DateInput.jsx#L393) which value is for "cs-CZ" locale `day. month. year` **with spaces between it**. 
It cause that next swich (https://github.com/wojtekmaj/react-date-picker/blob/master/src/DateInput.jsx#L400) do not catch `month` and `year` part, because it starts with space. 
It can be fixed by adding before switch `.map(x=>x.trim())` (or expand IE filter fix) but I don't know if it is the best solution.

**Comment by wojtekmaj** [comment]
Hey @PetrSnobelt,
sorry for the long wait.
Would you please give me more details about your testing platform (Browser, OS)? React-Date-Picker highly depends on native date format functionality and I can't reproduce it on Windows 10 on any browser.

**Comment by wojtekmaj** [comment]
Or actually, would you kindly check if `bugfix/cz-CZ-displays-only-day` branch does the trick for you?

**Comment by wojtekmaj** [comment]
The patch is now included in 6.3.3. Please let me know if it works for you!

**Comment by PetrSnobelt** [comment]
Hi, sorry for the long delay before the response. New version works correctly

**Comment by wojtekmaj** [comment]
Thanks for feedback! I'm glad it works :)
