### ISSUE TITLE
Prevent calendar auto-close on date select

### ISSUE THREAD

**Issue by guido732** [wojtekmaj/react-date-picker#230]
Hi! this may not be a bug but more of a question.

I'm using the component for a specified design which requires to have an `Accept` button at the bottom so that once you pick the date, you can manually give the OK and set the date. Currently it auto-closes once you pick a date. 

Is this somewhat possible to achieve by passing a custom prop I may have missed to the component? Something like `autoClose={false}` . Am I missing something that could allow me to do this? 

##### By the way, thank you for adding the non-stylized version import, absolute life saver!
Thanks!

**Comment by wojtekmaj** [comment]
Should be relatively easy to implement, I'll keep it on my list!

Thanks for the kind words too :)
