### ISSUE TITLE
Is it possible to manually set the `value` which is shown on the input when having an array of dates?

### ISSUE THREAD

**Issue by sebarickert** [wojtekmaj/react-date-picker#231]
Hi 👋 

is it possible to manually set the value for the input whilst still setting the date range `value={[startDate, endDate]}`?

**example:**

I have two separate DatePicker components working together and setting the `start` and `end` date to the state with `onChange`.

```
<DatePicker
  value={[startDate, endDate]}
  onChange={setStartDate}
  name="startDate"
/>
```

```
<DatePicker
  value={[startDate, endDate]}
  onChange={setEndDate}
  name="endDate"
/>
```

I need to use the date range feature for the calendar and trying to set it for both DatePicker components. My issues is, `value` with an array shows the first item in the array as the value of the input.

This is fine with `startDate`, but with `endDate` I'd need it to show `endDate` value in the input.

Is this possible?

**idea:**

Maybe something like this would work nicely?

`value` prop would still work, but adding a new prop e.g. `valueInput` which would overwrite `value` props first array item.

```
<DatePicker
  value={[startDate, endDate]}
  valueInput={endDate}
  onChange={setEndDate}
  name="endDate"
/>
```

**Comment by wojtekmaj** [comment]
Why not simply

```js
<DatePicker
  value={startDate}
  onChange={setStartDate}
  name="startDate"
/>
```
```js
<DatePicker
  value={endDate}
  onChange={setEndDate}
  name="endDate"
/>
```
? 🤔 

BTW there's [React-DateRange-Picker](https://github.com/wojtekmaj/react-daterange-picker) package you might be interested in, too!
