### ISSUE TITLE
Changing value to an invalid one should still trigger onChange & cause native input to be updated

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-date-picker#234]
Currently `input.value && input.checkValidity()` is used to check all inputs and if the condition is valid for all of them, it triggers onChange. It should just check if some unwanted characters like "abc" are not present in the field, if anything.

In other words, as long as the date created from inputs is a valid JavaScript Date, then native input should be updated and onChange should be triggered.

**Comment by hannupekka** [comment]
Not sure if our issue is direcly related to this but here is a minimal example: https://codesandbox.io/s/zen-waterfall-b075i

Notice the format we are using. If you try to input date "11.1" (by pressing 1 three times) by keyboard, picker throws an error that we are unable to catch. So in our case it would be nice that it wouldn't throw an error but still trigger `onChange` where we could decide what to do. 

Or maybe have some way to pass custom validation callback.

**Comment by wojtekmaj** [comment]
That doesn't seem related - this looks like omitting year causes React-Date-Picker to crash because it it's the only field it can no longer create a valid date without.

**Comment by wojtekmaj** [comment]
This will be implemented in https://github.com/wojtekmaj/react-date-picker/pull/250. Then, in next major version we'll change the default behavior.
