### ISSUE TITLE
Possibility to set openToDate

### ISSUE THREAD

**Issue by milennaj** [wojtekmaj/react-date-picker#237]
Hi,

Is there a way to position to a specific date when date picker is opened? For example I have a minDate value set in the past(01-01-2020). I would like to position datePicker to 02-01-2020 not the current month.

Example:
        <DatePicker
          format={"dd-MM-yyyy"}
          openToDate={minStartDate !== null ?  addDays(minStartDate , 1) : undefined}
          minDate={minStartDate !== null ? minStartDate : undefined}
          value={startDate}
          onChange={date => setStartDate(date)}
        />

Can something like this be implemented?

Thanks

**Comment by wojtekmaj** [comment]
You mean opening the calendar on a specific date? You can do this! Props that aren't consumed by Date Picker itself are passed to the Calendar component. You should check activeStartDate - more details in [React-Calendar docs](https://github.com/wojtekmaj/react-calendar).

**Comment by milennaj** [comment]
Hi,

It works, great :) . Thank you.
