### ISSUE TITLE
question: Is it possible to exclude some dates between minDate and maxDate

### ISSUE THREAD

**Issue by nnmlss** [wojtekmaj/react-date-picker#244]
I need to create a booking form, with minDate and maxDate, but also some periods in between also single dates should be disabled also. Is it possible to achieve this with your component?

**Comment by nnmlss** [comment]
I need to create a booking form, with minDate and maxDate, but also some periods in between also single dates should be disabled also. Is it possible to achieve this with your component?

**Comment by wojtekmaj** [comment]
tileDisabled prop might help!

**Comment by nnmlss** [comment]
thanks for your reply but I can't find the **tileDisabled** prop into your documentation here in github, do you have some extendend version somewhere or explanation how can I use this prop?

**Comment by wojtekmaj** [comment]
Ah sorry, was in a rush. Thought it's [React-Calendar](https://GitHub.com/wojtekmaj/react-calendar). Soo... You can disable dates in the calendar but not really in the picker itself. Can't apply this logic to native date picker, so you would need to either validate the dates yourself too, or rely 100% on the calendar.

**Comment by nnmlss** [comment]
I have found it - into the react callendar page. 
Edit:
I have seen your answer now, thanks for your reply. It works into the picker also, I just tested it and it can mark some date as disabled and do not respond on the click event. Aaa.. you mean you can't stop the user to type a disabled date into the text field..? Actually I do not want a text field, only a calendar view so probably I will use your callendar react component instead.
