### ISSUE TITLE
Year with 4 digits in textbox

### ISSUE THREAD

**Issue by gyto23** [wojtekmaj/react-date-picker#246]
I know that it was already mention in #212, but I still have a question why should you support more that 4 digits in they year. Are you expecting the application to be working more that 10k years? LOL.

Another idea is to support a moment format to use from here https://momentjs.com/docs/#/displaying/format/. If you support `y` as just a 4+ digit for year, you might can consider to support `YYYY` to just support strait 4 digits of the year.

**Comment by wojtekmaj** [comment]
I'm in no position to define what this component can and cannot be used for. Maybe someone would like to build React based sci-fi game and want to schedule their starship fleet to attack the enemy on January 15th 19455? ;)

Defining maxDate should limit the number of digits possible to enter in date picker :)
