### ISSUE TITLE
Input is not responding to random numbers

### ISSUE THREAD

**Issue by gyto23** [wojtekmaj/react-date-picker#247]
I was playing around with Input of the date picker and I found an issue that cause input to do not clear out if you press on the clear button in case where the values are 000/000/00000

![image](https://user-images.githubusercontent.com/54277098/77681707-c2457a00-6f63-11ea-99e1-9d6c241b7027.png)

In addition I found issue where you manually trying to put a 01 to the field and it creates a double 001, just type 0, and then 1

![image](https://user-images.githubusercontent.com/54277098/77681800-e6a15680-6f63-11ea-9ffb-43b0ce9d3933.png)

**Comment by wojtekmaj** [comment]
Related to #234. React-Date-Picker is not aware of invalid numbers even being inputted in the first place, so resetting value doesn't really work in this case. I see this design flaw now and I'm planning to fix it in the next major release.
