### ISSUE TITLE
Overwrite baseClassName

### ISSUE THREAD

**Issue by gyto23** [wojtekmaj/react-date-picker#248]
Is it possible to overwrite the baseClassName, in case of using several of `react-...-picker`? Most of the library are sharing the same styles and I already wrote my own custom one, but staking class together in same file make our life repeated:

![image](https://user-images.githubusercontent.com/54277098/77694388-edd25f80-6f77-11ea-8e57-fc4c71e5ef79.png)

**Comment by wojtekmaj** [comment]
Neat idea. It's currently not possible but I don't see a reason why it wouldn't be 👏
