### ISSUE TITLE
closeCalendar does not exist on type DatePickerProps

### ISSUE THREAD

**Issue by frankhn** [wojtekmaj/react-date-picker#255]
Hi, Am using trying to close the calendar with the above props method in react typescript, yet seems not to figure out what is going on here. 

Any help is would be highly appreciated.

**Comment by wojtekmaj** [comment]
Try 8.0.1 that was released just today

**Comment by frankhn** [comment]
> Try 8.0.1 that was released just today

Seems not helping either. I tried npm install react-date-picker@8.0.1  the version you specified, unfortunately, this happens

![image](https://user-images.githubusercontent.com/33962360/78603208-02f09d80-7858-11ea-8dbb-944d6c9f6cd2.png)

**Comment by kousenlsn** [comment]
Any news on this issue? I'm also needing it, thanks!

**Comment by jtieu-r7** [comment]
Looks like it doesn't exist yet. Also looks like the component type is incorrect since it's extensible with a constructor, contrary to the current type @8.0.5:

```js
declare module "react-date-picker" {
  export default function DatePicker(props: DatePickerProps): JSX.Element;

  export interface DatePickerProps extends CalendarProps {
    calendarClassName?: string | string[];
    calendarIcon?: JSX.Element | null;
    className?: string | string[];
    clearIcon?: JSX.Element | null;
    dayPlaceholder?: string;
    disabled?: boolean;
    format?: string;
    isOpen?: boolean;
    monthPlaceholder?: string;
    name?: string;
    onCalendarOpen?: () => void;
    onCalendarClose?: () => void;
    required?: boolean;
    showLeadingZeros?: boolean;
    yearPlaceholder?: string;
  }
}
```

Seems like it needs to be updated?

**Comment by wojtekmaj** [comment]
PRs regarding TypeScript are welcome. I'm not maintaining this part of the package because I'm not familiar with TypeScript.

In the future, typings will be moved to DefinitelyTyped.

**Comment by wojtekmaj** [comment]
Closed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51210
