### ISSUE TITLE
Can we strict user to enter 0??

### ISSUE THREAD

**Issue by nikhil-tayal** [wojtekmaj/react-date-picker#258]
At present, a user can enter as many zeroes as he wants. 
We can not restrict the user while entering because of onChange method called after we select the complete date!!

e .g 000000011/0000012/2020

**Comment by SukPavel** [comment]
Exactly same problem. The problem of this is when user try to manually write date with leading zeros: 01/01/2020, the "auto formating" generates date like this 010/12/020

EDIT: solved in version 8.1.x, just update package @nikhil-tayal

**Comment by nikhil-tayal** [comment]
Thanks @SukPavel !!!

Do we need to do something extra??? Or it is a by default feature.
Because it is still appending 0

**Comment by SukPavel** [comment]
@nikhil-tayal 

No need to do something.

Appending only one or multiple like your initial example 00000011/000000012....? If there is only one zero, you have probably set **showLeadingZeros** prop?

**Comment by nikhil-tayal** [comment]
No, I am using only format prop!!

**Comment by SukPavel** [comment]
@nikhil-tayal can you write the format  you are using?

**Comment by nikhil-tayal** [comment]
format={dd/mm/y}

**Comment by SukPavel** [comment]
just use d/m/y ;) dd means two-cipher day, mm means two cipher month. And if you force two-cipher day and month, the zero is prepended.

**Comment by wojtekmaj** [comment]
This was resolved in e8643de4177ea785b202c8f83c22c64e45dd6187. Typing values longer than max length causes focus to jump to the next field.
