### ISSUE TITLE
Incompatible with NextJS

### ISSUE THREAD

**Issue by aladinflux** [wojtekmaj/react-date-picker#259]
The CSS is directly imported from `node_modules`.  Instead of importing it, you should allow us to import it ourselves. This will allow us to use unpkg.com to include the css file or use our own css parsers.

This also makes the library incompatible with the popular NextJS, here's why:
https://github.com/zeit/next.js/blob/master/errors/css-npm.md

**Comment by matthewLeFevre** [comment]
@aladinflux why did you close this issue? I think this is valid.

**Comment by aladinflux** [comment]
@matthewLeFevre, import from 'entry.nostyle'
```
import DatePicker from 'react-date-picker/dist/entry.nostyle'
```

**Comment by wojtekmaj** [comment]
For the record, next major version will ship with no styles by default - you'll have to import them by yourself.
