### ISSUE TITLE
datepicker one day off behind the day what is selected.

### ISSUE THREAD

**Issue by pixaque** [wojtekmaj/react-date-picker#263]
Hi,

I am facing datepicker one day off issue. I searched for it and find some solutions but they didn't work. 

This is what is happening I select today's date but it is saving as yesterday. I found the issue involves timezone. Can you please help me how I can solve it?

Regards,
Asad Ullah

**Comment by wojtekmaj** [comment]
React-Date-Picker saves local date, midnight. What's likely happening is that you're reading it as an ISO string which by definition is UTC time (+0:00 timezone).

For example, if you're in Berlin, your midnight will happen 1 hour before it happens in London (UTC). Hence the off-by-one error.

To solve this, read the local date.

❌ .toISOString()
❌ .toUTCString()
❌ .getUTCFullYear()
❌ .getUTCMonth()
❌ .getUTCDate()

✅ [getISOLocalDate()](https://github.com/wojtekmaj/date-utils#getisolocaldate)
✅ .toString()
✅ .getFullYear()
✅ .getMonth()
✅ .getDate()
