### ISSUE TITLE
The prop `value` is marked as required in `DatePicker`

### ISSUE THREAD

**Issue by meandillar** [wojtekmaj/react-date-picker#265]
I'm using eslint to check propTypes. When initialising the DatePicker with a `null` value everything works as expected but I get an error in the console:

`Warning: Failed prop type: The prop "value" is marked as required in "DatePicker", but its value is "null".`

I saw in another issue that you're working on typings so forgive me if this is already being addressed. Thanks for the great library.

**Comment by wojtekmaj** [comment]
I'm afraid I'm not working on typings - this is entirely up to the community.

However seeing that in console would suggest a React propTypes error, not TS typings error. React propTypes for `value` prop are not set as `isRequired`. Perhaps your component is named the same way, or you overwrite the propTypes?

**Comment by meandillar** [comment]
Wow that's exactly what happened - I had overlooked my component named _DatePicker_ where I had the `value` prop was set to `isRequired`. Thanks for the help and apologies for the wasted time!
