### ISSUE TITLE
Easier styling

### ISSUE THREAD

**Issue by paambaati** [wojtekmaj/react-date-picker#268]
[react-hook-form](https://github.com/react-hook-form/react-hook-form) by @bluebill1049 is an incredibly powerful (not to mention popular) library for using forms with React hooks.

I've been trying to get `react-date-picker` to work with RHF, and I'm able to get the value out to RHF's controlled component wrapper. However, I'm having trouble getting the `isOpen` prop to work - see https://codesandbox.io/s/friendly-varahamihira-mclrc?file=/src/App.js

What am I doing wrong?

**Comment by paambaati** [comment]
On further debugging, I now realize that the control does work (I can see the CSS classes change on toggling `isOpen`). Is there an easier way to style the component?

Here's my challenge currently -

I use Next.js, which supports only importing CSS files globally (see https://nextjs.org/docs/basic-features/built-in-css-support). This means I'd have to globally import the datepicker CSS (small as it might be), which isn't clean and possibly prone to clashing with other future components.

If I try to use CSS modules or an inline `css` prop to the component, it does not work. Would it be possible to supply `css` or `styles` as a prop that overrides the component's defaults (so we can customize its look as well as build invalid states)? I think this would be a happy medium.

**Comment by wojtekmaj** [comment]
You can pass your own className and calendarClassName, if you need to implement styling on your own using libs like styled-components. Adding `style` prop isn't a good idea in my opinion because there are tons and tons of elements inside the wrapper that would need to be styled this way.
