### ISSUE TITLE
How to add time of day to selected date?

### ISSUE THREAD

**Issue by phtmgt** [wojtekmaj/react-date-picker#269]
Have you thought about forcing a time of day instead of the default 00:00? This is useful in variety of situations: For example, when I want to select a time period I'd like to have two datepickers, one starts from 00:00, the other should end at 23:59:99 (in order to include the start date and end date). Or, I'd like to force 12:00 in order to avoid some issues with timezones (I know this is not the correct way to do it, but anyways, it is useful in some cases). Now, the way to do this is to modify the date object in the onChange function, which is ok, but clumsy).

A simple time prop would be great (defaulting to 00:00:00).

**Comment by wojtekmaj** [comment]
Interesting idea :) By the way, check out [React-DateTimeRange-Picker](https://github.com/wojtekmaj/react-datetimerange-picker).

**Comment by wojtekmaj** [comment]
```js
function MyApp() {
  const [value, onChange] = useState(new Date());

  function onChangeWithTime(nextValue) {
    const nextValueWithTime = new Date(nextValue);
    nextValueWithTime.setHours(21);
    nextValueWithTime.setMinutes(37);

    onChange(nextValueWithTime);
  }

  return (
    <DatePicker
      onChange={onChangeWithTime}
      value={value}
    />
  );
}
```
