### ISSUE TITLE
Add option to format display date with leading zeros

### ISSUE THREAD

**Issue by u3k** [wojtekmaj/react-date-picker#27]
i.e. to produce dates with zero padding like '01/01/2018'

**Comment by wojtekmaj** [comment]
Hey @u3k,
thank you for the suggestion!
I have prepared a solution on a separate branch. It is more tricky than it sounds, as we use number inputs for entering dates to ensure validity, accessibility and good mobile support.
I don't want to create a messy, complicated code though, so my solution requires React 16.2 and Babel 7. That means that it will take a while to test it properly!

**Comment by u3k** [comment]
Thanks! We are on latest react/ts so it's for totally OK :)

**Comment by wojtekmaj** [comment]
In that case, check out what I'm up to on `feature/show-leading-zeros`. But please allow me some more time until it goes to production :) There's tons other people who rely on `react-date-picker`.

**Comment by u3k** [comment]
👍
