### ISSUE TITLE
Interacting with Calendar and then changing the date does not cause Calendar view to update

### ISSUE THREAD

**Issue by HARIKSREEE** [wojtekmaj/react-date-picker#271]
I am using react version 16+
and  react-date-picker version 8.0.1
When I initially change the year value in the input, the calendar is showing the correct year. After selecting the date for first time, changes in the year input is not updating the calendar.

Steps:
1) Click any of the input field (day||month||year)
2) calendar will be displayed
3) select a date
4) calendar will close
5) click the input field again and calendar will be opened
6) change the year value by typing in the year field

Expected:
Calendar should be updated with the exact year typed

I am using the locale: "en-US" and format "MM-dd-yyyy"

**Comment by HARIKSREEE** [comment]
![image](https://user-images.githubusercontent.com/38159830/82992704-2399d000-a01d-11ea-9ec3-0d9c139783bf.png)

**Comment by HARIKSREEE** [comment]
The same issue exists for month field also.  Only update happening is for date value changes

**Comment by wojtekmaj** [comment]
Confirmed bug. We're using React-Calendar improperly; value is controlled, but activeStartDate is not. Selecting date in Calendar causes it to set activeStartDate internally, so Calendar is no longer updating.

The fix would be to 
* either calculate activeStartDate in DatePicker
* or add a feature in React-Calendar not to set activeStartDate on date selection, and use it
* or add a feature in React-Calendar to only set state if props callbacks are not provided, and use it

**Comment by HARIKSREEE** [comment]
Thanks for the quick update @wojtekmaj 
I tried the first method and it worked.
Changes made:
Created a new state variable to keep the ```activeStartDate ``` value.
And set the ```activeStartDate ``` when ever the date changes and also on ```onActiveStartDateChange```.
The update on ```onActiveStartDateChange``` is needed as we need to keep the drill down/up and month/year navigation working.

**Comment by wojtekmaj** [comment]
This bug will be fixed in React-Date-Picker once a discussion in https://github.com/wojtekmaj/react-calendar/issues/358 reaches conclusion. Please be patient. It's highest priority of them all at the moment.

**Comment by HARIKSREEE** [comment]
Thank you @wojtekmaj 
I put the above changes only as a quick fix for my project. I will be following the latest changes to this repo.

**Comment by Attamjot** [comment]
> Thanks for the quick update @wojtekmaj
> I tried the first method and it worked.
> Changes made:
> Created a new state variable to keep the `activeStartDate ` value.
> And set the `activeStartDate ` when ever the date changes and also on `onActiveStartDateChange`.
> The update on `onActiveStartDateChange` is needed as we need to keep the drill down/up and month/year navigation working.



> Thanks for the quick update @wojtekmaj
> I tried the first method and it worked.
> Changes made:
> Created a new state variable to keep the `activeStartDate ` value.
> And set the `activeStartDate ` when ever the date changes and also on `onActiveStartDateChange`.
> The update on `onActiveStartDateChange` is needed as we need to keep the drill down/up and month/year navigation working.

What all changes have you made, will be great if you can share the code ?

**Comment by TemaniH** [comment]
@Attamjot 
You can see solution - https://github.com/wojtekmaj/react-calendar/issues/358#issuecomment-634847447

It didn't work for me for v3.x, so you can look at my W/A too:
https://github.com/wojtekmaj/react-calendar/issues/342#issuecomment-716738084

**Comment by angenue** [comment]
putting activeStartDate={new Date(year, month, 1)} in the calendar worked
