### ISSUE TITLE
Manual input of year populates year later than 2000

### ISSUE THREAD

**Issue by DGugov** [wojtekmaj/react-date-picker#276]
I am using "react-calendar": "3.1.0" and "react-date-picker": "8.0.1".
When I try to populate the date with my keyboard (for example 2/2/1955) I cant imput year different than 2000 and something. The moment I press "1" the year 2001 is automatically selected.

4th and 5th of June I did not experience this issue.
![Calendar](https://user-images.githubusercontent.com/66615271/84016263-b293da00-a985-11ea-8025-c2fb6e3e6ba2.jpg)

**Comment by wojtekmaj** [comment]
This shouldn't be the case, check the demo page:
https://projects.wojtekmaj.pl/react-date-picker/
Maybe you're parsing the date on your own somehow?

**Comment by DGugov** [comment]
This issue no longer occurs.
