### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by shreyaa1** [wojtekmaj/react-date-picker#277]
when importing 
`import DatePicker from "react-date-picker/dist/entry.nostyle";` 
working properly but when I am trying to import 
`import DatePicker from "react-date-picker"` 
according to README file getting the error 
`{"message":"Unexpected token '.'","stack":"/node_modules/react-calendar/dist/Calendar.css:1}`

can someone help me with this issue?

**Comment by wojtekmaj** [comment]
If you want to use React-Date-Picker with default styles auto-imported, your bundler needs to be configured properly to compile CSS files.

**Comment by wojtekmaj** [comment]
Webpack users: An example of how you can solve this issue:

```js
 { 
   test: /\.css$/, 
   use: [ 
     'style-loader', 
     'css-loader', 
   ], 
 }, 
```
