### ISSUE TITLE
onChange callback not fired when all values is not valid

### ISSUE THREAD

**Issue by SergSisense** [wojtekmaj/react-date-picker#279]
hi
the issue is: 
i can change/set the values -directly(not using picker) by using DateInput
as a result i can set invalid values like: month = 13, 55, ...etc; day = 66, -21, ...etc.
in: https://github.com/wojtekmaj/react-date-picker/blob/master/src/DateInput.jsx#L420
you can see there a validation for all values and if one of them is not valid - onChange is not called

if there a way i can get values even if they are invalid - i will like to know

thanks

**Comment by wojtekmaj** [comment]
There's no way React-Date-Picker could return invalid date. This is intentional as there's an effort to make it work as closely as possible to the native date picker input field.
