### ISSUE TITLE
Reset Date

### ISSUE THREAD

**Issue by dgarciaoxfera** [wojtekmaj/react-date-picker#28]
Hi Wotejmak,

If I delete the date of dateinput and leave the date empty, the calendar doesn´t change the date internally. I think this can be confusing, I attach image. In my opinion, value should be null, for this case and dispatch  onChange.

![image](https://user-images.githubusercontent.com/32450063/33723525-3d0ebc7a-db6d-11e7-97b1-2a2108bd20af.png)

Once the component has a date, there is no way for the user to reset the date. 
A reset icon would be a great addition.

Thanks!

**Comment by wojtekmaj** [comment]
Hey @dgarciaoxfera,
in v6.5.0 I have added a clear button.
I'm tracking React-Date-Picker's behavior when input is cleared manually by erasing all fields in #29.

Let me know what you think!

**Comment by dgarciaoxfera** [comment]
Perfect, thanks!
