### ISSUE TITLE
Month Dropdown displayed when using MMM format

### ISSUE THREAD

**Issue by Nilotpalchanda** [wojtekmaj/react-date-picker#280]
I'm trying to bring month format in **MMM** but whenever I'm trying this format the drop down is coming instead of input box. So, is there is any way to remove the drop down in the **MMM** format?

Code
-------
`  <DatePicker
            format="dd-MMM-yyyy"
            dayPlaceholder="DD"
            monthPlaceholder="Mon"
/>`

Preview 
-------------
![image](https://user-images.githubusercontent.com/20255543/86781433-826e5280-c07b-11ea-9d4d-f0dc1e7fa28a.png)

**Comment by kjkunal94** [comment]
I am facing a similar problem in my project, where I do not want a drop-down, when using the dd-mon-yyyy format.
A quick response or fix for this , would be highly appreciated.

**Comment by brunopego** [comment]
I'm having the same issue.

**Comment by brunopego** [comment]
@wojtekmaj are you aware of this problem?

**Comment by wojtekmaj** [comment]
MMM is Month abbreviated in [Unicode Technical Standard #35](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) we're following as stated in documentation.

According to this table, use M or MM for numeric month.

**Comment by manchaary** [comment]
So is it possible to use MMM without Select?

**Comment by wojtekmaj** [comment]
@manchaary What would you like to see instead of Select then?

> According to this table, use M or MM for numeric month.

**Comment by abhidatta0** [comment]
if MMM or MMMM is there, then it should be just month name string ("May") instead of HTML select.
Also, how I can format it to something like 2nd May , 2024.

**Comment by Louis-Ramsey** [comment]
> if MMM or MMMM is there, then it should be just month name string ("May") instead of HTML select. Also, how I can format it to something like 2nd May , 2024.

were you able to achieve this please

**Comment by wojtekmaj** [comment]
> if MMM or MMMM is there, then it should be just month name string ("May") instead of HTML select.
> Also, how I can format it to something like 2nd May , 2024.

And how would the users be able to provide the value? By typing month name? This won't work well, especially with i18n support.
