### ISSUE TITLE
Tabbing through without entering picker

### ISSUE THREAD

**Issue by mgandley** [wojtekmaj/react-date-picker#284]
Not sure the best way to accomplish this without negatively impacting accessibility, but here goes.

I have a form that has this datepicker, among other inputs.  When I tab through the inputs, I land on the datepicker.  Then, to get to the next input, I need to tab through the buttons in the calendar (of which there are many) before I can get to the next input.  You can see this behavior on the sample component on https://projects.wojtekmaj.pl/react-date-picker/.

Could we perhaps expose a bool prop like `openCalendarOnFocus` that allows us to say "don't open the calendar automatically when the datepicker is focused"?  Then if the user chooses, they could click or keyboard nav to the calendar icon button and use that to open the calendar dropdown.  You could set the default to true to preserve existing behavior.

Thoughts?  Am I missing something obvious?

**Comment by mgandley** [comment]
Submitted merge request #286 to add this enhancement.

**Comment by jdm000** [comment]
+1
