### ISSUE TITLE
React-Date-Picker with React-Calendar

### ISSUE THREAD

**Issue by sirsaula** [wojtekmaj/react-date-picker#287]
Is it possible to have the react-date-picker on selection show the react-calendar https://github.com/wojtekmaj/react-calendar component? Reason being is the current calendar that appears on selection does not allow for aria labels for the 'next' and 'previous' button and we are seeking to resolve that for accessibility issues..

Thanks

**Comment by sirsaula** [comment]
forgot to tag you @wojtekmaj  :-) ^ quick question above

**Comment by wojtekmaj** [comment]
No need to tag me.

This _is_ React-Calendar. You can totally pass ARIA props to it - as per README props are passed to React-Calendar as well.
