### ISSUE TITLE
/'s not lining up with dates

### ISSUE THREAD

**Issue by kemalturksonmez** [wojtekmaj/react-date-picker#289]
![react-date-picker](https://user-images.githubusercontent.com/56357795/89590946-37746600-d806-11ea-88f0-36bbd4525877.png)
I've played around with the css for the divider and have had no luck with it. Any clue what might be causing this?

**Comment by wojtekmaj** [comment]
Without the code? Nope

**Comment by kemalturksonmez** [comment]
`<DatePicker
                            selected={ this.state.date }
                            onChange={ this.onDateChange }
                            value = { this.state.date }
                            maxDate = {this.state.today}
                            name="date"
                            clearIcon= { null }
                            dateFormat="dd/MM/yyyy"
                        />` 
This is how I call it in my file.
