### ISSUE TITLE
Erasing date input completely should be considered a valid, empty value

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-date-picker#29]
When the user erases all inputs, it should be considered a valid, empty value. It should trigget onChange with null.

**Comment by wojtekmaj** [comment]
Works as designed in 6.7.0.

**Comment by TimTruston** [comment]
Good

**Comment by GuidovdRiet** [comment]
Still receiving: `Uncaught Error: Invalid date: Invalid Date` when I use an empty string `''` value.
