### ISSUE TITLE
openTo prop

### ISSUE THREAD

**Issue by cobbdb** [wojtekmaj/react-date-picker#291]
First off, LOVE this library. Finally a dirt-simple to use react datepicker, so thank you.

I'd love to see an `openTo` prop that will allow the calendar to open directly to the "century", "decade", or "year" view. This would be very handy for things like DOB fields so users can quickly go way back in time for older birthdates.

**Comment by wojtekmaj** [comment]
You can use `defaultView` prop in React-Calendar to do just that.

You can also use controlled prop `view` like so:
https://codesandbox.io/s/react-calendar-default-decade-xk5t1
