### ISSUE TITLE
Next/Previous button doesn't work >= v7.11.0

### ISSUE THREAD

**Issue by pedrofsantoscom** [wojtekmaj/react-date-picker#292]
The following buttons don't work on v7.11.0 onward. I need to revert back to v7.10.0 for them to work.
Tested on chrome, FF and edge on windows 10, gatsby project, react v16.12.0

![image](https://user-images.githubusercontent.com/2325978/91432169-42e10d00-e859-11ea-91a1-592fc1bf0998.png)

From what i've been able to find, if i set `ReactCalendar.activeStartDate` prop, the navigation arrows don't work.

**Comment by wojtekmaj** [comment]
activeStartDate should overwrite internally handled activeStartDate value, so this is expected. If you want to use activeStartDate, then you need to also handle `onActiveStartDateChange` yourself.

**Comment by pedrofsantoscom** [comment]
@wojtekmaj works, thanks

**Comment by AKclown** [comment]
thanks
