### ISSUE TITLE
Disable manual input.

### ISSUE THREAD

**Issue by BKDruby** [wojtekmaj/react-date-picker#293]
How can I disable manual input date from keyboard?
I wan't to leave possibility use calendar UI only.

**Comment by snesjhon** [comment]
This is was the suggested solution: 

https://github.com/wojtekmaj/react-date-picker/issues/78

**Comment by sinups** [comment]
> How can I disable manual input date from keyboard? I wan't to leave possibility use calendar UI only.

onFocus={document.activeElement.blur()}

**Comment by workforbala** [comment]
mentioned fix has been deprecated  .

https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-user-input
