### ISSUE TITLE
Thai Year Problem (Buddhist)

### ISSUE THREAD

**Issue by goodlythink** [wojtekmaj/react-date-picker#294]
Thai Year Problem in input
Calendar display 2563
but input display 2560
set locale="th"

**Comment by wojtekmaj** [comment]
Can you include a reproduction CodeSandbox based on e.g. https://codesandbox.io/s/react-date-picker-c430c ?

**Comment by goodlythink** [comment]
https://codesandbox.io/s/react-date-picker-forked-3n9qw

**Comment by wojtekmaj** [comment]
Thanks for reporting this. For now, fixed the date to display 2020 instead of static text of 2560, but full support of Buddhist year will come.
