### ISSUE TITLE
Missing css in certain unique cases.

### ISSUE THREAD

**Issue by Pixelatex** [wojtekmaj/react-date-picker#30]
In my case, I use a static builder that has real issues with css imported by modules. I need to declare them in the head or import them as a file in my css folders.

To get this one working, my only option was copying the css from the src and pasting it in a new file in my scss file.

It might be handy to have a css link to link to in the head.

**Comment by wojtekmaj** [comment]
Hey @Pixelatex,
if you don't want to have CSS imported by modules, there's a special entry file for you. Then, you can add CSS manually using whatever method you'd like. Please mind that you would need to import styles of react-calendar and react-date-picker. More details [here](https://github.com/wojtekmaj/react-date-picker#custom-styling)!
