### ISSUE TITLE
Workspaces warning when installing React-Date-Picker using yarn

### ISSUE THREAD

**Issue by jeffrson** [wojtekmaj/react-date-picker#305]
Hi,

in a yarn workspaces monorepo (actually controlled by lerna, but this shouldn't matter) we get this warning for every dependency to

react-date-picker
and
@wojtekmaj/react-daterange-picker

**Workspaces can only be enabled in private projects.**

This is probably because of the "workspace" entry in package.json and obviously missing "private": true

**Comment by wojtekmaj** [comment]
Shoot. That shouldn't have been published as a workspace. Didn't know this would also apply to anyone using the package.

You're using React-Date-Picker as a dependency from npm, not cloning it yourself from GitHub or anything like that?

**Comment by jeffrson** [comment]
> You're using React-Date-Picker as a dependency from npm

Yes.

The warning appears, when I run yarn inside the "outer" workspace. I don't know how yarn/yarn2 handles this.

**Comment by wojtekmaj** [comment]
Fixed in v8.0.3. Thanks!

**Comment by jeffrson** [comment]
Thanks for the quick fix!
