### ISSUE TITLE
Overlay while the input is focused

### ISSUE THREAD

**Issue by moecantplay** [wojtekmaj/react-date-picker#306]
Hi,
I'm wondering if anyone has ever implemented this datepicker with an overlay background behind it when focused, so just the datepicker and the input field would be visible while the rest of the page is covered with an transparent overlay..
If so, how can we achieve that? If not, would anyone mind helping me out?

**Comment by wojtekmaj** [comment]
Since React-Date-Picker is built with a bunch of normal inputs, all you have to do is wrap it with your own div and e.g. listen for onFocus and onBlur events to trigger an overlay. It should be not much different than implementing it for a single text input.
