### ISSUE TITLE
Month abbreviations

### ISSUE THREAD

**Issue by AndriiBoiko1** [wojtekmaj/react-date-picker#307]
Hi @wojtekmaj, just wondering if there is any possibility to show short months abbrs in picker
like this:
![image](https://user-images.githubusercontent.com/57752495/93859578-797a3e00-fcc6-11ea-8865-712ebb485e0e.png)

instead of
![image](https://user-images.githubusercontent.com/57752495/93859392-40da6480-fcc6-11ea-82b5-322665eee550.png)

Thanks in advance!

**Comment by wojtekmaj** [comment]
Sorry, not possible since the value has to be typed in and supporting text values in all languages would be a nightmare.
