### ISSUE TITLE
Issue with iOS in Japanese

### ISSUE THREAD

**Issue by sjahan** [wojtekmaj/react-date-picker#310]
Hi, 

I have a strange issue with your lib, which works great in any other condition, but only in Japanese on iOS.
Here is a video that will show you what happens: [https://streamable.com/lwfsrt](https://streamable.com/lwfsrt)

When any of the three sub inputs is filled, the content gets automatically selected, the contextual menu appears (that is the black box you can see in the video, it shows classic options cut/copy/paste/etc), then the content of the input gets deleted.

Have you ever seen this? Do you know if your component could trigger some strange iOS behavior by accident?

The thing is, I do not reproduce it with a basic input type number having the same parameters than the one generated by the React component. What is also strange is that this behavior only triggers when the field is full. For the year input for example, if you only type 3 digits, no problem. It happens only when the last digit is typed, so that's why I suppose it is something implemented.

Thank you by advance!

**Comment by wojtekmaj** [comment]
@sjahan Is there any chance to "revive" the video?
