### ISSUE TITLE
Global CSS imports in node_modules are not supported by Next.js

### ISSUE THREAD

**Issue by WhatNodyn** [wojtekmaj/react-date-picker#313]
Next.js is a framework that adds some niceties around React (among which, heavy automation for Server-Side Rendering).

Due to time constraints, we had to migrate to it from pure React, and while ensuring our code is fully working we ran across the following error:
```
./node_modules/react-calendar/dist/Calendar.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-date-picker/dist/entry.js
```

This is a voluntary decision taken by the Next.js team, as is documented [here](https://err.sh/next.js/css-npm).

Is there anyway this library could be altered (e.g. a secondary entrypoint that doesn't automatically include the required stylesheets, so that we may do so in our repository's `pages/_app.js`)?

**Comment by viiiprock** [comment]
You should import with nostyle and with css separately
Read more here
https://github.com/wojtekmaj/react-date-picker#custom-styling
