### ISSUE TITLE
Add support for Buddhist year

### ISSUE THREAD

**Issue by PokerJava** [wojtekmaj/react-date-picker#317]
locale={'th'}
 output 01/11/2020
 wrong display anno domini

**Comment by wojtekmaj** [comment]
Related to #294

**Comment by thuanKJ** [comment]
Hi @wojtekmaj ,
Do you have any updates for this issue?  This one is blocking me right now. I'm trying to find a solution to work around when i pick a date with 'th-TH' locale.

**Comment by wojtekmaj** [comment]
Implemented in https://github.com/wojtekmaj/react-date-picker/pull/403, but this needs a but more testing.

**Comment by PokerJava** [comment]
help me pls version 8.4.0 not working year out put 2565 current year
