### ISSUE TITLE
Show only Year picker

### ISSUE THREAD

**Issue by IronTony** [wojtekmaj/react-date-picker#321]
Hi all,

I am a little bit stucked in showing only a date picker with the year. So my question: is it possible to show only a Year picker? Can you show an example code please?

Thank you in advance

**Comment by wojtekmaj** [comment]
Option 1: Use `maxDetail="decade"`. This will cause the calendar not to display any views more detailed than decade, so the most detailed input will be year.

Option 2: Use `format` prop as instructed in README.
