### ISSUE TITLE
Serverside rendering broken by navigator access in Input.js

### ISSUE THREAD

**Issue by jorrit** [wojtekmaj/react-date-picker#323]
Since 8.0.4 I can't build my application because of the following error:

> ReferenceError: navigator is not defined
>     at Object.<anonymous> (node_modules\react-date-picker\dist\DateInput\Input.js:25:20)

This broke in commit 7c6af9dc1b85da949258fc5e80058740ea8ad81e.

I see two solutions:

1. prefix `navigator.userAgent...` with `typeof navigator !== 'undefined' && `.
2. Move `navigator.userAgent.match(/ Edge\/1/)` to the `if` statement in onFocus().

**Comment by wojtekmaj** [comment]
Thanks for reporting.

Ad 1 - actually window can be undefined in some envs as well. I think the best approach would be:

```js
const isEdgeLegacy = (
  typeof window !== 'undefined' && 'navigator' in window
  && navigator.userAgent.match(/ Edge\/1/)
);
```

**Comment by wojtekmaj** [comment]
v8.0.5 released. Thanks again
