### ISSUE TITLE
Overflow: auto causing visibility issue, no access to rootBoundary property

### ISSUE THREAD

**Issue by n8turner** [wojtekmaj/react-date-picker#326]
When the date picker is inside a parent container which has an overflowY set to scroll, or auto the popup is cut off and invokes a horizontal scroll in the container instead of breaking the container border and appearing on top as a popup. Because we are not able to access the Popper library implementation or set the rootBoundary property in order to ignore the overflow.

**Comment by wojtekmaj** [comment]
I'm not sure if I fully understand the issue. This library is not using Popper.
