### ISSUE TITLE
Provide prop to suppress select menu for month names

### ISSUE THREAD

**Issue by austincondiff** [wojtekmaj/react-date-picker#327]
I prefer the up/down arrow key navigation when increasing/decreasing numbers. I am expecting the same even if I format the date to use month names. I would like a prop to allow for this behavior even when dates are formatted to use month names.

**Comment by wojtekmaj** [comment]
Month names are using `<select>` for value selection and I don't see how we could (and whether we should) change the default, well-known dropdown behavior.
