### ISSUE TITLE
Clicking on abbreviated / full month name opens both the select dropdown input and the calendar

### ISSUE THREAD

**Issue by adhirchakravarti** [wojtekmaj/react-date-picker#328]
Hi Wojciech Maj,

First off, love the react-date-picker, thanks for creating it!

When using the abbreviated / full month name in the `format` prop (`format="dd MMM y"`), clicking the month name or the caret symbol next to it, opens both the select dropdown input and the calendar. The select dropdown is open and covering the calendar behind it. I wanted to attach a screenshot but Github is having issues with it.

When clicking the month name or the caret symbol, is there a way to prevent the select dropdown input from opening and only open the calendar?  Or when clicking the month name or the caret symbol, is there a way to prevent the calendar from opening and only open the select dropdown input?

**Comment by adhirchakravarti** [comment]
Reproducible example: https://codesandbox.io/s/frosty-galileo-d2rrh?file=/src/App.js

**Comment by makis-spy** [comment]
TIP: You can add css pointer-events:none to prevent the drop down opening
