### ISSUE TITLE
days include full date in date picker (how to hide/disable?)

### ISSUE THREAD

**Issue by yanfaingold** [wojtekmaj/react-date-picker#330]
![image](https://user-images.githubusercontent.com/9849056/101633075-7114e200-3a2f-11eb-8ecb-06a92f59c7ea.png)

how i can hide or disable the following label after the day, *  

i dont want to display the date text followed after the day

**Comment by wojtekmaj** [comment]
Looks like you provided your own `formatShortWeekday` which did this.
