### ISSUE TITLE
Calendar won't close due to Issues with Fit component

### ISSUE THREAD

**Issue by lmaldonadoch** [wojtekmaj/react-date-picker#334]
# Configuration
* React Version
> 16.12
* jQuery version
> 3.5.1

# Behavior
When using the unstyled version of the component, the `Fit` component has no `position: relative` and the children do not have a `position: absolute` properties, which prevents it from closing after setting the date even when explicitly adding the property in the component.

# Expected behavior
For the calendar to close on date selection.

# Console Error:
```
<Fit />'s child does not have absolute position. You should apply `position: absolute` to it.
<Fit />'s parent does not have relative position. You should apply `position: relative` to it.
```

**Comment by wojtekmaj** [comment]
Well, for Calendar to be positioned properly you will need to follow the development warnings you're seeing. No way around it really.
