### ISSUE TITLE
Select week

### ISSUE THREAD

**Issue by aktoriukas** [wojtekmaj/react-date-picker#336]
is there a way for me to make this on hover select week, not a day?
the way it returns day - have no issues with that, only on hover would like it to mark the whole week, not a day.
is there an easy way of doing this?
thanks in advance.

**Comment by wojtekmaj** [comment]
I'd implement my own onChange function that, when called, finds week start/end and sets a range as value. For this to work properly the way to go would be [React-DateRange-Picker](/wojtekmaj/react-daterange-picker).

As to hover styling, that would be possible with React-Calendar's tileClassName, but it'd be quite a lot of work to get right.

**Comment by aktoriukas** [comment]
To find a start and end of the week - done this already using date-picker (working very well) , but as for hover, still can't come up with a solution. If class names would contain weekday, that would be an easy task.
