### ISSUE TITLE
Disable a list of dates

### ISSUE THREAD

**Issue by liamtarpey** [wojtekmaj/react-date-picker#337]
Hi there - I couldn't see in your docs that there's a way to disable given days anywhere.

We essentially want to fetch some data from our backend and disable certain days based on this list (format TBD, can be adjusted to what works here)

Any way to do this currently? Same question for your other cool library `react-time-picker` :)

Thanks!

**Comment by wojtekmaj** [comment]
[You can do this in the calendar](https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-disable-tiles) used by React-Date-Picker, but not in React-Date-Picker itself.
