### ISSUE TITLE
Date picker crashes in IE11

### ISSUE THREAD

**Issue by erikiva** [wojtekmaj/react-date-picker#338]
When I type the date in IE11, it seems correct on month and date but then when it gets to the year it crashes with the error 
`SCRIPT5022: Invalid date: Mon Jan 01 1 00:00:00 GMT-0500 (SA Pacific Standard Time)`

IE11 is supposed to have support for internationalization but even so I've tried adding the polyfill and this is still happening. 
The locale is locale="en-US"
Any suggestions on what might be wrong would be appreciated.

**Comment by erikiva** [comment]
It seems as you type it initially tries to create a Date with year 1 which in IE11 is an Invalid Date. 
This line above for the minValue also generates an Invalid Date
`var defaultMinDate = new Date('0001-01-01');`
![Screen Shot 2021-01-29 at 8 35 21 AM](https://user-images.githubusercontent.com/13215331/106281373-23398080-620d-11eb-8884-d9001f415ecd.png)

**Comment by wojtekmaj** [comment]
It's actually a much simpler problem than internationalization. 

IE handles this date just fine, it's when it gets passed to new Date() again that messes it up :D Apparently IE has a problem with dates < Unix 0, when passed to Date() constructor. Have a look:

![obraz](https://user-images.githubusercontent.com/5426427/106284358-6c0c2c00-6243-11eb-9937-bb0d276ab982.png)

**Comment by wojtekmaj** [comment]
Ok, I added a check so that new Date() isn't called if we already have a date to begin with, which should, at least looking at the last 2 lines of the screenshot above, help with the issue.

#338

Could you have a look, maybe apply this fix by hand in your project and see if this fixes the problem? Once we have the confirmation it works for you we can release the fix.

**Comment by erikiva** [comment]
I tried and it fixes it but it doesn't show the numbers being typed,  then the same error comes up this time from the Calendar.

**Comment by wojtekmaj** [comment]
Thanks so much!

It is expected - calendar suffers from the very same issue and I raised this PR https://github.com/wojtekmaj/react-calendar/pull/480 to fix the same issue there.

Release incoming 👀 We'll see if we could fix the numbers not shown, although that would be a different ticket.

**Comment by erikiva** [comment]
Thank you so much!

**Comment by wojtekmaj** [comment]
v8.0.7 released with the fix applied to both React-Date-Picker and React-Calendar.

**Comment by erikiva** [comment]
All good now, Thank you!!

**Comment by wojtekmaj** [comment]
Like, _all_? The numbers typed are also shown?

**Comment by erikiva** [comment]
Yes, for some reason it wasn't picking up my changes for the calendar, and you were faster in fixing the whole thing so just upgraded and now it's ok. I am running IE in parallels and sometimes it's weird.
