### ISSUE TITLE
Support for range

### ISSUE THREAD

**Issue by jm-maniego** [wojtekmaj/react-date-picker#34]
Here's a skeleton of what I currently have: https://codesandbox.io/s/nn6zj9nzp0

I think `react-calendar` already supports the range picker, would be great if we separate the props for calendar from the `react-date-picker` props.

maybe something like..

```
<DatePicker 
  ...
  value={startDate}
  calendarProps={{
    returnValue: "range",
    value: [startDate, endDate]
  }}
/>

<DatePicker 
  ...
  value={endDate}
  calendarProps={{
    returnValue: "range",
    value: [startDate, endDate]
  }}
/>
```

**Comment by wojtekmaj** [comment]
Hey @jm-maniego. Thanks for suggestion! I can definitely implement react-calendar's `range`. However, that might not be what you expect - it allows you to return an array of values. For example, if you pass `maxDetail="month"`, selecting January would return you `[new Date(2017, 0, 1), new Date(2017, 0, 31, 23, 59, 59, 999)]`. If you want to select *two separate dates*, I'm actually working on it, but it's going to be a separate package. Stay tuned and I'll deliver ;)

**Comment by jm-maniego** [comment]
awesome thanks @wojtekmaj, will look forward to it :)

**Comment by wojtekmaj** [comment]
Hello @jm-maniego,
on my GitHub, there's react-daterange-picker which is based on react-date-picker. Unfortunately, this name is taken and current maintainers are not willing to give it up, so I'm not publishing it on npm just yet.

**Comment by wojtekmaj** [comment]
Published under `@wojtekmaj/react-daterange-picker`, so closing.
