### ISSUE TITLE
Global CSS cannot be imported from within node_modules. Read more: https://err.sh/next.js/css-npm Location: node_modules\react-date-picker\dist\entry.js

### ISSUE THREAD

**Issue by eeeman1** [wojtekmaj/react-date-picker#340]
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-date-picker\dist\entry.js

**Comment by davistran86** [comment]
This is what I use:

```
import DatePicker from "react-date-picker/dist/entry.nostyle";
import "react-date-picker/dist/DatePicker.css";
import "react-calendar/dist/Calendar.css";
```

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

Perfect solution. @eeeman1  @davistran86

**Comment by renzoyyan** [comment]
> import DatePicker from "react-date-picker/dist/entry.nostyle";
> import "react-date-picker/dist/DatePicker.css";
> import "react-calendar/dist/Calendar.css";

It's not working for meee.  `next": "13.0.5`

**Comment by renzoyyan** [comment]
`(node:16620) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Creating an optimized production build  
Failed to compile.

./node_modules/react-calendar/dist/Calendar.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\react-date-picker\dist\entry.js

Import trace for requested module:
./node_modules/react-calendar/dist/Calendar.css
./node_modules/react-date-picker/dist/entry.js

./node_modules/react-date-picker/dist/DatePicker.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\react-date-picker\dist\entry.js

Import trace for requested module:
./node_modules/react-date-picker/dist/DatePicker.css
./node_modules/react-date-picker/dist/entry.js

Import trace for requested module:
./node_modules/react-date-picker/dist/DatePicker.css
./node_modules/react-date-picker/dist/entry.js
`
