### ISSUE TITLE
autoFocus={true}  this prop is missing in index export

### ISSUE THREAD

**Issue by aktechbee** [wojtekmaj/react-date-picker#341]
I am trying to use this prop as per mentioned in document but my eslint is showing error that this prop is not available. 

Please add or let me know any workaround

**Comment by wojtekmaj** [comment]
I'm happy to accept all contributions related to typings shipped with this package.

**Comment by Spacylab** [comment]
Seems like it's just a missing type
#363

**Comment by wojtekmaj** [comment]
Fixed in c097c3eba25d92620e2b3a778a5b654e1a9f4842.
