### ISSUE TITLE
`showYearPicker` and `selectsRange` props are mutually exclusive and they shouldn't be

### ISSUE THREAD

**Issue by lgrosz** [wojtekmaj/react-date-picker#343]
```
<DatePicker
  onChange={onChange}
  startDate={startDate}
  endDate={endDate}
  showYearPicker
  selectsRange
  inline
/>
```

I expect to be able to select two dates and have the years be highlighted. This is not the case.

Example is the same as [this](https://reactdatepicker.com/#example-date-range-for-one-datepicker), but with `showYearPicker` added.

**Comment by lgrosz** [comment]
Upon further investigation, it just seems the `showYearPicker` is totally borked. [This](https://reactdatepicker.com/#example-range-quarter-picker) doesn't work either if you use that prop.

**Comment by wojtekmaj** [comment]
Wrong repository.
