### ISSUE TITLE
Using with Formik, cannot pass an `id` or `name` attribute to the input

### ISSUE THREAD

**Issue by flora8984461** [wojtekmaj/react-date-picker#344]
Hi, thanks for this library, it's really nice.

I have not seen anyone is using it with Formik in the issues. When I use it with Formik, it shows the following warning:

```
Warning: Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:
    <button class="react-calendar__tile react-calendar__tile--active react-calendar__tile--range react-calendar__tile--rangeStart react-calendar__tile--rangeEnd react-calendar__tile--rangeBothEnds react-calendar__month-view__days__day" type="button" style="flex-basis: 14.2857%; max-width: 14.2857%; overflow: hidden;"><abbr aria-label="January 6, 1970">6</abbr></button>
```

It seems due to the lack of attribute "id" and "name". Though I already used id and name (it should be passing by {...field} and {...rest}, and I added again id and name)

```
      <Field name={name}>
        {({ form, field, meta }) => {
          const { setFieldValue } = form
          const { value } = field
          return (
            <>
              <DatePicker
                id={name}
                {...field}
                {...rest}
                name={name}
                onChange={val => setFieldValue(name, val)}
                value={(value && new Date(value)) || null}
                className="form-control"
              />
            </>
          )
        }}
      </Field>
```
It seems that the DatePicker is not passing the id and names to its input.  

Any help is appreciated. Thanks in advance!

**Comment by wojtekmaj** [comment]
Here's the thing: React-Date-Picker creates a set of inputs, so it's not possible to use `id` at all. `name` is passed to a hidden native date input, which is not editable by hand.

We would need to have support for, hm... Fieldsets? in Formik to make it work somehow.

**Comment by aaronmw** [comment]
@wojtekmaj Does this not fundamentally break accessibility? How are we meant to connect a DateInput to a `label` without wrapping the entire field with the label (which is not always feasible)??

Maybe the `id` should be applied to the first of those input fields — the real purpose is to forge the connection between label and value, and enable things like clicking the label to focus the field. Having the `id` on the first input would check those boxes, no?

**Comment by a-dominiak** [comment]
I know it's been a long time, but please update it to make it accessible. Id prop for each input or change id to be for first input. Either one would be fine.
