### ISSUE TITLE
Different Date Picker Styling when importing styles from library

### ISSUE THREAD

**Issue by sanchits1999** [wojtekmaj/react-date-picker#346]
![image](https://user-images.githubusercontent.com/59724468/108801760-98099b80-75bc-11eb-92c2-0446de1ddfe5.png)

import DatePicker from "react-date-picker/dist/entry.nostyle";
import "react-date-picker/dist/DatePicker.css";
import "react-calendar/dist/Calendar.css";

<DatePicker
           onChange={onChange}
           value={value}
           isOpen={true}
/>

**Comment by wojtekmaj** [comment]
Your page styling applied to general elements like buttons affects Calendar styling. That's how CSS works. You will have to write your own custom styles.
