### ISSUE TITLE
Calendar modal should only come on click of icon

### ISSUE THREAD

**Issue by snrohit** [wojtekmaj/react-date-picker#347]
Hi,

Can this requirement be achieved?

User should be able to type in the dates freely, without calendar modal being pop out.
Calendar should only come when clicked on calendar icon explicitly.

Any help will be appreciated.

Thanks

**Comment by wojtekmaj** [comment]
This is idiotic, but try passing an onFocus function that throws an error.

There definitely should be a way to disable this functionality though, so I'm going to add a flag.
