### ISSUE TITLE
Input name

### ISSUE THREAD

**Issue by mollynordh** [wojtekmaj/react-date-picker#35]
Should have a prop to pass a name to the input field for post/get.

**Comment by mollynordh** [comment]
Never mind! It was already there, haha :) Sorry!

**Comment by wojtekmaj** [comment]
Wait, is it? I genuinely thought it's a defect when I read your first post 😂

**Comment by wojtekmaj** [comment]
Fixed in v6.6.2. Also propagated it to react-time-picker and react-datetime-picker. Thanks for suggestion!

**Comment by vishalTechnoFreek** [comment]
is it something  like it displays the name like placeholder
