### ISSUE TITLE
Manually toggle focus using refs

### ISSUE THREAD

**Issue by ovidiumihaibelciug** [wojtekmaj/react-date-picker#352]
Hello, first of all thank you for creating this awesome library!

I'm struggling to find a way to manually focus on the input. I tried adding a ref, but it doesn't include a focus method. I saw that there is an autoFocus prop, however, I'm looking for a method to focus on the day part of the input when a key (enter) is pressed. So if the user presses on "enter" I would like to trigger a focus on the first input (the day input in my case). 

Is this possible now?

**Comment by hjrobinson** [comment]
You can add a ref to your DatePicker component and then access the children:
```
const month = ref.current.wrapper.children[0].children[0].children[1];
const day = ref.current.wrapper.children[0].children[0].children[3];
const year = ref.current.wrapper.children[0].children[0].children[5];
```
