### ISSUE TITLE
In IE11 manual Input on already selected input value does not change value unless existing value is deleted

### ISSUE THREAD

**Issue by amolksagar** [wojtekmaj/react-date-picker#354]
Hi, 

I am using the latest version of react-date-picker(8.1.1) . All works fine with google chrome however in Internet explorer 11 I am facing an issue. If a date is already selected, say 22/12/2019 then if the user selects the day , it gets highlighted. In chrome user can directly start typing on top of the selection(overwrite) and it works but in IE11 when the user types to overwrite (when date/month/year is highlighted) the input actually works as TAB

Ex: If I selected the date (22 in this case), 22 gets highlighted, then when I start typing to overwrite on it , the control goes to 12(month) and then to 2019(year). As a developer, I know that i have to clear the field by pressing backspace or delete BUT the production end user wont be knowing this and will raise this as an issue saying the dates are not getting selected/overwritten

IE11 version : 11.1158

**Comment by wojtekmaj** [comment]
Not sure what you mean exactly, do you mean that on IE 11 previous value in input doesn't get auto selected?
