### ISSUE TITLE
Quarter / Year Picker keyboard navigation appears to be broken

### ISSUE THREAD

**Issue by ezulu** [wojtekmaj/react-date-picker#356]
For Days / Month picker the keyboard navigation appears to be working fine. For quarter and year pickers the keyboard navigation does not transition from the arrow keys in the header of the calendar piece to the different selections of the calendar. I took the gif from your website with the example but couldn't find an open issue for this.

![reactDatePickerKeyboard](https://user-images.githubusercontent.com/26664528/115386589-366e4380-a19f-11eb-923a-199fb9236183.gif)

**Comment by wojtekmaj** [comment]
Wrong repository. Sorry!
