### ISSUE TITLE
closeCalendar prop not working

### ISSUE THREAD

**Issue by Paxatax** [wojtekmaj/react-date-picker#361]
Hi,

I'm unable to keep the calendar open after selecting a date.

```
import DatePicker from 'react-date-picker/dist/entry.nostyle';
import 'react-date-picker/dist/DatePicker.css';
import 'react-calendar/dist/Calendar.css';

<DatePicker
    isOpen
    closeCalendar={false}
    onChange={onChange}
    value={value}
/>
```

package.json
```
"react-date-picker": "^8.1.1"
```

Is this a bug or am I doing something wrong? Running it in a NextJS app.

Thanks in advance.

**Comment by hjrobinson** [comment]
Yeah, I'm having the same problem. I'm not using NextJS.

**Comment by IsbahAhmed** [comment]
I am having same problem but i want to close date picker on select.

**Comment by hjrobinson** [comment]
Since I was having the opposite problem you could try using the 8.2.0 release but you won't have the latest updates.

**Comment by wojtekmaj** [comment]
Caused by https://github.com/wojtekmaj/react-calendar/pull/388
