### ISSUE TITLE
Focus jumps over month if typing fast

### ISSUE THREAD

**Issue by kolyasya** [wojtekmaj/react-date-picker#366]
https://user-images.githubusercontent.com/3371143/121714873-f4021c80-cae6-11eb-908f-7888c2541968.mov

Faced a strange issue when typing numbers fast. Actually it wasn't intentional, this is the speed I'm really usually type with.
So if I hit 2 numbers quick the focus goes directly from the day to year input.

Any ideas how this can be fixed?

**Comment by hungyiloo** [comment]
I'm getting this issue too. If typing slowly, it doesn't skip the month field and behaves normally. If typing fast, it skips over the month field.

**Comment by hjrobinson** [comment]
Yeah, I'm having the same issue. If there were even an option to turn off the automatic jumping I would be fine with it. The chicken may have come before the egg. This solution to the issue below may have caused the issue:

https://github.com/wojtekmaj/react-date-picker/issues/128
