### ISSUE TITLE
Omitting locale prop does not properly use default value of browser locale as stated in README

### ISSUE THREAD

**Issue by judemorrissey** [wojtekmaj/react-date-picker#368]
Observed on `8.2.0`

Using on both Firefox and Chrome, I realized the Calendar has Monday as the first day of the week, versus my expected Sunday as the first day of the week as my locale is `en-US`, as verified using `window.navigator.language` _and_ using `getUserLocale()` from the `get-user-locale` package as is used in `src/shared/dateFormatter.js`. If I explicitly provide the `locale` prop with either a literal `"en-US"` value, or use the returned value by `getUserLocale()`, then I get the expected calendar format. Perhaps the `getFormatter()` function receives a truthy value that does not trip the `|| getUserLocale()` part of the code in `dateFormatter.js`?

I have a workaround right now using `getUserLocale()` explicitly, but I thought I'd take the time to file a bug. Thank you for the wonderful library!

**Comment by wojtekmaj** [comment]
If `locale` provided to `formatMonth`/`formatShortMonth` was `true`, then `MonthSelect`'s `propTypes` warning would be triggered. So that ain't it.

However, in `MonthView`, there's a function called `getCalendarTypeFromLocale`. Could you debug it to see what's the input and output of this function? This should give us an idea on what's going on.

**Comment by judemorrissey** [comment]
Hello! I would love to help, I naïvely tried to add `console.log` where I grepped `getCalendarTypeFromLocale` in the `react-calendar` package, but alas for some reason I did not seem to hit my log lines. For context, I haven't really done much debugging of node packages I consume, I've just done enough to occasionally look in the code to see how a package works internally.

Would you please be so kind to better direct me how I can help? I am afraid that there is possibly something with our setup using Webpack that could be omitting my logs.
