### ISSUE TITLE
Use of DatePicker in an edit form

### ISSUE THREAD

**Issue by JohnZonneveld** [wojtekmaj/react-date-picker#371]
Trying to implement DatePicker into my react application. While creating an object I have no problem at all. If I select a date of 03/09/2002 it is saved as 2002-03-09 in the database. 
However when I try to display it in my EditForm, although I set the value as value={tour.date} I see a value of 2002-03-08 in the react-date-picker__inputGroup class.
When I click on the field my app crashes with the following errors/warnings.
Warning: Failed prop type: Invalid prop value supplied to Days
Warning: Failed prop type: Invalid prop value supplied to TileGroup
Uncaught Error: Failed to get month from date: 2002-03-09
The above error occurred in the component
Uncaught Error: Failed to get month from date: 2002-03-09

No clue what I am doing wrong, but it has something to do with the value that I set in DatePicker.
Is the format wrong of my date?

**Comment by Aliendre** [comment]
try this:

//on state
const [editDate, setEditDate] = useState(new Date(tour.date));

//on DatePicker
value={editDate}
