### ISSUE TITLE
Need to open datepicker window with specific month and year

### ISSUE THREAD

**Issue by Tanmay2711** [wojtekmaj/react-date-picker#374]
Hi Team,

we are using datepicker component and we have requirement as below - 
When user clicks on datepicker icon, user should see specific month and year page. Default it opens with current month and year and today's date selected.

E.g. If we want to allow user to select any date from month and year in past or future, then after opening datepicker window user should see that specific month and year.
if we want end user to select any date in November 2020 then need provision to open datepicker window with November as month and 2020 as year selected as oppose to current month and year.

Thanks and Regards,
Tanmay

**Comment by wojtekmaj** [comment]
Use [React-Calendar](https://github.com/wojtekmaj/react-calendar)'s `activeStartDate`. Just pass it to `DatePicker`.
