### ISSUE TITLE
Input value not updated when out of boundary date is typed 

### ISSUE THREAD

**Issue by usematics** [wojtekmaj/react-date-picker#375]
- Create a DatePicker setting a minDate and maxDate. Let's say max date is 31/07/2021
- Type a date out of the maxDate, for example 20/9/2021
- Click out of the calendar to hide the calendar
- The month (or day) will show a red background, keeping the typed date. The value will remain with the initial value, but will not update the displaying date. 
- Since it is incorrect date, the onChange event is not triggered and one can not manually validate the date.

The red background is not enough for end-users to know is invalid, and there is a miss match between the date shown and the value. If this is submitted, the end-user will believe they are sending the desired incorrect date.

Is it possible to instead of the wrong date, display back the initial value. Or some way to validate the date to alter the user ?

```js
import React, {useState} from "react";
import DatePicker from 'react-date-picker'

const DateC = () => {
  
  let minDateDate = new Date();
  minDateDate.setDate(minDateDate.getDate() );
  let maxiDate = new Date ();
  maxiDate.setDate(minDateDate.getDate()+31)
  const [maxDate, setMaxDate] = useState(maxiDate);
  
  const [fecha, setFecha] = useState(minDateDate);
  function setTheDate(lfecha){
    setFecha(lfecha)
  }
  return(
      <>
        <DatePicker
            id={"fecha"}
            value={fecha}
            onChange={(value) => {
              setTheDate(value)
            }}
            minDate={minDateDate}
            maxDate={maxDate}
        />
        <div>{fecha.toLocaleDateString()}</div>
      </>
      
  )
}

export default DateC;
```

**Comment by wojtekmaj** [comment]
This is tricky because if we pass initial value, or null value, in onChange when invalid date is typed, then we could get very unexpected results when React-Date-Picker is used as controlled input. My suggestion would be to listen for onInvalid.
