### ISSUE TITLE
Typings and prop types inheritance

### ISSUE THREAD

**Issue by kapke** [wojtekmaj/react-date-picker#38]
I've seen that there is a lot of typings (and prop types) which are clones of calendar ones. What about using:
* interface inheritance in terms of typings
* any way of extending object (spread, `Object.assign`) in terms of prop types

I think it could make things simpler to maintain. Especially that when the calendar is rendered, it has passed all props from date-picker.

**Comment by wojtekmaj** [comment]
Hey @kapke,
I think that's a great idea. It is indeed a pain for me to update it all. To be honest though, my TS skills are weak and although Pull Requests are welcome, I'm trying to focus on what I'm good at at the moment :)

**Comment by kapke** [comment]
I should have a while in this weekend or early next week so I will open a PR for this.
