### ISSUE TITLE
Add option to disable specific days of the week

### ISSUE THREAD

**Issue by avargasma** [wojtekmaj/react-date-picker#382]
Add option to disable specific days of the week, for example day 1 or 2.
Something like this.

![image1](https://user-images.githubusercontent.com/14371662/132463000-b4483556-f2f7-4162-9786-f382be7e4610.PNG)

**Comment by wojtekmaj** [comment]
Duplicate of https://github.com/wojtekmaj/react-date-picker/issues/337
