### ISSUE TITLE
Disable only the days in the calendar

### ISSUE THREAD

**Issue by FrancoPaez** [wojtekmaj/react-date-picker#385]
Because when I use the tileDisabled attribute, not only are the selected days disabled, but also the months, years and decades?

You can check the code with the example in this [DEMO](https://codesandbox.io/s/select-calendar-hiring-d6re6?file=/src/App.js:1325-1337)

I attach screenshots just in case

The days are fine

![1](https://user-images.githubusercontent.com/82821596/133943439-7f310ff6-45b0-477f-a800-14f04ea1f6d3.PNG)

The months, years and decades are not right

![2](https://user-images.githubusercontent.com/82821596/133943440-95783284-210c-4d55-90b5-1fce6a81573b.PNG)

![3](https://user-images.githubusercontent.com/82821596/133943442-98f29601-1814-451e-bb4e-83be07139964.PNG)

Code snippet

`      
tileDisabled={({ activeStartDate, date, view }) =>
        date.getDay() === 0 || date.getDay() === 6
      }
`

**Comment by wojtekmaj** [comment]
`tileDisabled` function runs on all tiles, not only day tiles. You also need to check `view` value.
