### ISSUE TITLE
Disable HTML 5 message bubble

### ISSUE THREAD

**Issue by sam-kaz** [wojtekmaj/react-date-picker#386]
We are using this date picker with react hook forms with custom validation for our date picker, which is working fine the only issue we are having is on an invalid date its shows the message on the form with HTML5 message bubble (see below). Is there any way we could disable the message bubble on an actual control, instead of applying "noValidate" on the form itself.

![obraz](https://user-images.githubusercontent.com/5426427/149756161-5911bc4f-3739-4679-aa4a-5d6a43fff29d.png)

Many Thanks!

**Comment by wojtekmaj** [comment]
There are a couple of ways you can tackle this:

* Use `<form noValidate>`, but this will disable ALL native form validation rules
* Use `event.preventDefault()` in `onInvalid` callback; with a bit of additional logic to keep autofocus on error working correctly: https://codesandbox.io/s/react-date-picker-disable-native-validation-y89xz
