### ISSUE TITLE
Demo on website won't let me type "09092014" (Firefox)

### ISSUE THREAD

**Issue by indignant** [wojtekmaj/react-date-picker#389]
Hey there, I'm looking for a date picker to use and I noticed the date picker demo on your project's page doesn't work as expected in OSX Firefox (93.0). It seems to work fine in Chrome.

Steps to reproduce:
1. go to https://projects.wojtekmaj.pl/react-date-picker/ in FF
2. note the date is set to today (while writing this it shows 10/07/2021)
3. focus the month input by clicking it
4. type a different month (I tried both '9' and '09')
5. note the month doesn't change, but skips to the day input and changes that instead

Focusing the month input and typing "09092014" results in:
<img width="261" alt="Screen Shot 2021-10-07 at 11 35 56 AM" src="https://user-images.githubusercontent.com/69015187/136427162-55da1293-1080-4a3e-ad0d-85c4992b6ea3.png">

**Comment by wojtekmaj** [comment]
Kinda fixed in 03337f8 but not really.

See https://github.com/wojtekmaj/react-time-picker/issues/92
