### ISSUE TITLE
Issue with iOS 15 and Australian English

### ISSUE THREAD

**Issue by tony-seng** [wojtekmaj/react-date-picker#396]
Hi,

Since that iOS 15 got released on iPhone, we experienced an issue with the lib when the phone is in English (Australian).

The year input disappears and the last divider before the year is not "/" but "/17". 
When we tried to input a date, the page crashed with the following error: "Invalid date: Invalid Date"

Cf attached video and error stack.

Kind regards,

https://user-images.githubusercontent.com/46719529/143077687-13d01af5-4e1a-4a6b-bfd6-f06da7ffcfc1.mov

![Screenshot 2021-11-23 at 18 23 46](https://user-images.githubusercontent.com/46719529/143077807-9eedbb6c-bbf4-4c8d-9972-cf349b1a6fa2.png)

**Comment by wojtekmaj** [comment]
Congratulations, Apple!

![image](https://user-images.githubusercontent.com/5426427/143094685-027d570b-8f30-418d-84d2-b25e60e7e719.png)

**Comment by wojtekmaj** [comment]
Reported to WebKit here: https://bugs.webkit.org/show_bug.cgi?id=230827

**Comment by wojtekmaj** [comment]
Released in v8.3.6. Thanks!

**Comment by tony-seng** [comment]
Thank you! it works great
