### ISSUE TITLE
Allow for different date presentation formats - DD-MM-YYYY

### ISSUE THREAD

**Issue by TimTruston** [wojtekmaj/react-date-picker#40]
It would be really helpful to present date in different formats. At least for the very common ones like MM-DD-YYYY or DD/MM/YYYY. Having the date come first instead of month and using a dash instead of slash.

	<DatePicker
		format="dd-mm-yyyy"
		...
	/>

**Comment by wojtekmaj** [comment]
Hey @TechyTimo,
date format is automatically determined by using `locale` prop. Should you want to use e.g. American format - MM/DD/YYYY - you should set `locale="en-US"`. :)
You can play around with locales by choosing some options or manually typing them in [here](http://projekty.wojtekmaj.pl/react-date-picker/test/).

**Comment by manulou** [comment]
Thanks for the response! However there are use cases with international customers using a different date format then the current one (travelling agents who are using different devices to access the same environment). In this scenario the preferred date format comes from the backend but there is no way to set this on the date picker without attempting to guess the locale based on the format using some sort of lookup table.

Adding the format attribute would make react-date-picker much more customizable for these scenarios.

**Comment by wojtekmaj** [comment]
This will require a little more work from my side, but I agree that would be a valueable improvement :) Stay tuned!

**Comment by manulou** [comment]
Actually, looking at the implementation you are using 3 input type=number fields for displaying the date. So does that mean that you can't have dates with MM or DD (i.e. 01.05.2018)? The number fields won't render the extra 0 AFAIK?

**Comment by wojtekmaj** [comment]
That is correct. In fact, implementing this properly would require me to resolve #27 first.

**Comment by gabrieltosta96** [comment]
@wojtekmaj I would like to display dates like "29-May-2018", is that possible?

**Comment by duncanmwirigi** [comment]
I need date format YYYY-MM-DD, i have tried all ways of manipulating this date picker, but now working @wojtekmaj i need your help

**Comment by wojtekmaj** [comment]
@Gtosta96 No, date values are numeric only.

@Jucan You could use `order` CSS to reorder elements in flex wrapper, but that's generally not a good idea. What you want, for now it's not possible. :(

**Comment by wojtekmaj** [comment]
Good news! Support for custom format consisting of `y`, `M`, `MM`, `d`, and `dd` incoming 👀

**Comment by wojtekmaj** [comment]
Hi everyone,
React-Date-Picker 7.5.0 is out and supports `format` prop! Please refer to README for more details and list of supported tokens.

Happy coding!
