### ISSUE TITLE
Memory leak in dateFormatter.getFormatter

### ISSUE THREAD

**Issue by jorrit** [wojtekmaj/react-date-picker#405]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Commit 277e8796872e1806c3bf441898f91d5eb8b3bd5b introduced a cache for date formatters. One of the cache keys is the `options` object. However, at several locations this method is invoked with a new `options` object at every invocation. This means that the cache misses every time, as each cache key is a unique object.

The invocations of `getFormatter` in `DateInput.jsx` need to use static objects.

### Steps to reproduce

I've used the V8 Inspector to find the cause of my memory leak. This pointed me to Intl.DateFormatter instances.

I added `console.log('new instance');` to `node_modules/react-date-picker/dist/shared/dateFormatter.js` at the line that creates new instances and many lines were logged to the console.

### Expected behavior

`react-date-picker` should create a bounded amount of `Intl.DateFormatter` instances.

### Actual behavior

`react-date-picker` creates many `Intl.DateFormatter` instances while the application is running.

### Additional information

Personally I would stop exposing `getFormatter()` from `dateFormatter` and expose only the formatter that the rest of the code needs, similar to what you're doing with the exports `formatMonth` and `formatShortMonth`.

### Environment

- **Browser (if applicable)**: Chrome 99
- **React-Date-Picker version**: 8.4.0
- **React version**: 17.0.2

**Comment by jorrit** [comment]
@wojtekmaj Can I do anything to help fix this issue? I could make a PR, but there are many different solutions to this problem and I don't know which one you prefer.

**Comment by wojtekmaj** [comment]
Nope that's more than enough for me to work on, thank you - sorry, pretty busy in my private life :D Ironically, sick leave is what keeps my OSS projects going lately.

**Comment by jorrit** [comment]
Thanks a lot, hope you get better soon!

**Comment by jorrit** [comment]
@wojtekmaj Could you perhaps make a release with this fix? Thanks in advance!
