### ISSUE TITLE
Vite.JS support

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [wojtekmaj/react-date-picker#406]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

I am trying to migrate from webpack -> vite.js using React and Typescript

I am getting a runtime error. Everything seems to be fine from the compilation standpoint

```typescript
import DatePicker from 'react-date-picker';

              <DatePicker
                value={filterCriteria.document.uploadedFrom}
                onChange={(value: Date) => setFilterCriteria((previous) => (
                  {
                    ...previous,
                    document: {
                      ...previous.document,
                      uploadedFrom: value,
                    },
                  }
                ))}
                name="to_date_input"
                className="document__filter__input"
                clearIcon={null}
                calendarIcon={<FontAwesomeIcon icon={faCalendarAlt as IconProp} />}
                format="MM/dd/yyyy"
                calendarClassName="document__filter__calendar"
              />
```

When I attempted to migrate our DatePicker code I got the runtime error noted below.

Does this plugin support vite.js? Is there a way I can get around this error?

### Steps to reproduce

1. Setup basic Vite.js with Typescript application
2. Use datepicker
3. Run Vite preview
4. Notice error

![image](https://user-images.githubusercontent.com/6002111/159382444-e436fe3e-a17b-49fd-812a-c2ea8d0c3063.png)

### Expected behavior

Date picker displays properly with no error

### Actual behavior

Date picker does not display properly

### Environment

- **Browser (if applicable)**:  Vivaldi 5.1.2567.66 (Stable channel) (64-bit) 
- **React-Date-Picker version**:  "react-date-picker": "^8.4.0",
- **React version**: "react": "^17.0.2",

**Comment by wojtekmaj** [comment]
Addressed in b1adefe6f19cbbe2a483466d7fd7a7e54cc7d0d1 already.
