### ISSUE TITLE
Add day of week name to 'format' prop

### ISSUE THREAD

**Issue by desmondandersen** [wojtekmaj/react-date-picker#407]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Hi I am trying to implement a date picker that includes the day of the week name next to the date in the selection box. For instance: [Tuesday, 03/22/2022].

Right now the format prop only supports `y`, `M`, `MM`, `MMM`, `MMMM`, `d`, `dd`.

### Proposed solution

Would it be possible to add for `EEE` and `EEEE`? (https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table)

The tricky part would probably be handling invalid inputs, but perhaps that part of the selection field would be not directly editable.

**Comment by wojtekmaj** [comment]
I don't see how that could be reliably implemented. And if you select Monday, which Monday do you mean? The one before, or after currently selected day?

Best you could do is probably something like this:
https://codesandbox.io/s/react-date-picker-with-weekday-rkuvhf
