### ISSUE TITLE
Uncaught TypeError: Method get Intl.DateTimeFormat.prototype.format called on incompatible receiver undefined     at get format (<anonymous>)

### ISSUE THREAD

**Issue by cskiran** [wojtekmaj/react-date-picker#408]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

When trying to open the calendar i am getting **Uncaught TypeError: Method get Intl.DateTimeFormat.prototype.format called on incompatible receiver undefined**

 

### Steps to reproduce

click on the calendar icon 

### Expected behavior

calendar should be opened 

### Actual behavior

calendar is not getting opened instead Uncaught TypeError: Method get Intl.DateTimeFormat.prototype.format called on incompatible receiver undefined is thrown in console

### Environment

- **Browser (if applicable)**: Chrome(99.0.4844.82 ) 
- **React-Date-Picker version**:8.0.5 and "8.4.0"
- **React version**:17.0.2

**Comment by muiradams** [comment]
@cskiran, I'm having the same issue. Did you close the ticket because you solved it? If so, how?

**Comment by danielacorner** [comment]
@muiradams adding `format` prop seems to have fixed it for me

**Comment by danielacorner** [comment]
@muiradams resolved on my end by adding the `format` prop - but, same error reoccurs after I add `isOpen` prop, 

then, resolved by adding all `formatDay`-like functions formatDay, formatMonth, formatYear, formatLongDate, formatMonthYear, formatShortWeekday, formatWeekday ...
