### ISSUE TITLE
portalContainer missing in DatePickerProps interface

### ISSUE THREAD

**Issue by 27-7survey** [wojtekmaj/react-date-picker#409]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

In index.d.ts where is DatePickerProps interface definition portalContainer is missing

### Steps to reproduce

not applicable

### Expected behavior

not applicable

### Actual behavior

not applicable

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by 27-7survey** [comment]
As I see portalContainer is not available in latest version (8.4.0), but it is mentioned in README.md, so maybe it will be available in next release

**Comment by MatteoGauthier** [comment]
Any news about this issue ?

**Comment by mpham-r7** [comment]
https://github.com/wojtekmaj/react-date-picker/pull/412
