### ISSUE TITLE
Hi. can we show one character for "Week Days" like "S,M,T,W,T,F,S"

### ISSUE THREAD

**Issue by Jangwa** [wojtekmaj/react-date-picker#41]

**Comment by wojtekmaj** [comment]
Hey @Jangwa,
I suppose your feature request applies to [React-Calendar](https://github.com/wojtekmaj/react-calendar/) which is used by React-Date-Picker ;) And I have good news! In oncoming version 2.11.0 of React-Calendar, formatting weekdays will be supported by passing `formatShortWeekday` prop with your custom formatter function. When this happens, I'll update React-Date-Picker's documentation to reflect these changes in Calendar. Stay tuned!

**Comment by wojtekmaj** [comment]
Hello @Jangwa,
your request is now implemented in v6.7.0. Let me know what you think!
