### ISSUE TITLE
How can I disable manual input date from keyboard?  mentioned fix deprecated 

### ISSUE THREAD

**Issue by workforbala** [wojtekmaj/react-date-picker#417]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

How can I disable manual input date from keyboard? I wan't to leave possibility use calendar UI only.

mentioned fix for this issue is deprecated not working on all the browser. 
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-user-input

### Steps to reproduce

try not to type keyboard in put on date picker

### Expected behavior

keydown method so developer can disable user to enter.

### Actual behavior

keydown method so developer can disable user to enter.

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by carmelocatalfamo** [comment]
+1

**Comment by pitops** [comment]
Here is how i have done it

css
```
.react-date-picker__wrapper  .react-date-picker__inputGroup {
    pointer-events: none;
  }
```

js
```
const [openCalendar, setOpenCalendar] = useState(false);
    const calendarRef = useRef(null);

    useEffect(() => {
        const calendarComponent = document.querySelector('.react-date-picker__calendar')
        if (calendarComponent) {
            calendarRef.current = calendarComponent
        }
    }, []);

const toggleCalendar = (e) => {
        e?.preventDefault()
        if (e?.target && calendarRef.current.contains(e.target)) return
        setOpenCalendar(prev => !prev)
    }


return <div onClick={toggleCalendar}>
    <DatePicker
       // other props       
       isOpen={openCalendar}
       onCalendarClose={toggleCalendar}
    />
</div>
```
