### ISSUE TITLE
portalContainer doesn't seem to be working

### ISSUE THREAD

**Issue by ketanmodha** [wojtekmaj/react-date-picker#418]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Hi, Wanted to load the calendar using portalContainer doesn't seem to be working.

Tried this way to assign the existing div where I wanted to load the calendar

portalContainer={document.getElementById('div-name')}
portalContainer={document.getElementByClassName('div-name')}

### Steps to reproduce

1. Install react-date-picker
2. Imported date picker using `import DatePicker from "react-date-picker";`
3. Integrated DatePicker component
`<DatePicker
                        name="FieldName"
                        onChange={(value) =>
                          handleOnDateChange(value)
                        }
                        className="form-date-picker"
                        calendarIcon={<IconCalendar />}
                        clearIcon={<IconCancel />}
                        dayPlaceholder="dd"
                        monthPlaceholder="mm"
                        yearPlaceholder="yyyy"
                        showLeadingZeros={true}
                        format="MM-dd-yyyy"
                        portalContainer={document.getElementsByClassName(
                          "calendar-portal"
                        )}
                      />`

### Expected behavior

Expected behavior is to load the calendar insider the <div> assigned in portalContainer.

### Actual behavior

Calendar is still being loaded inside the same div element where it is being created.

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:
react-date-picker version: 8.4.0
react-version: 17.0.2

**Comment by wojtekmaj** [comment]
This feature has not been released yet.

**Comment by aesy** [comment]
@wojtekmaj When would you estimate a new version to be released, roughly speaking?

**Comment by wojtekmaj** [comment]
Roughly... Now.
