### ISSUE TITLE
Safari open 2 calendars native and custom

### ISSUE THREAD

**Issue by AnnaPetryuk** [wojtekmaj/react-date-picker#421]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

In Safari browser I click on month or year calendar buttons, browser open two datepickers (custom and native)

### Steps to reproduce

- click on datepicker icon
- on the top choose month/year
- select one of the option

### Expected behavior

Native Safari datepicker do not opened

### Actual behavior

Native Safari datepicker is opened

### Environment

- **Browser (if applicable)**: Safari 14.1
- **React-Date-Picker version**: 8.4.0
- **React version**: 17.0.2

**Comment by wojtekmaj** [comment]
Hmmm, can't reproduce, but I have Safari 15.5. Do you have a screenshot maybe?

**Comment by restrin-extensis** [comment]
I have Safari 15.5 as well and can repro by clicking on the whitespace between the year field and the close icon. 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/46825740/197866550-72988fc7-3089-4f75-b0a5-f934715b6b03.png">

Firefox 106.0.1 exhibits similarly
<img width="372" alt="image" src="https://user-images.githubusercontent.com/46825740/197866735-6ed2ec9c-c846-4112-8142-2a1bebca1d3b.png">

**Comment by semeniukb** [comment]
Hello, how to solve this bug?
