### ISSUE TITLE
Menu is not positioned when using portalContainer 

### ISSUE THREAD

**Issue by aesy** [wojtekmaj/react-date-picker#429]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

When setting `portalContainer` on the `DatePicker`, I would expect the menu to still be positioned under the input instead of completely leaving the positioning up to the user. It's possible that I have come to expect this because [this is how React Select works](https://react-select.com/advanced#portaling). React Select sets the following properties on the menu:

```css
position: absolute;
top: <y>px;
left: <x>px;
```

I guess this is me asking whether this really is the desired behavior or if it's up for discussion?

### Steps to reproduce

Use `portalContainer` to to render the calendar using a portal: `<DatePicker portalContainer={container} />`.

### Expected behavior

The positioning of the calendar is unchanged

### Actual behavior

The position of the calendar is relative to the portal container

**Comment by renzoyyan** [comment]
@aesy have u fix this issue? can u shareee it pls

**Comment by aesy** [comment]
No I don't have a fix, sorry
