### ISSUE TITLE
portalContainer doesn't work when value is set

### ISSUE THREAD

**Issue by MaximeBress** [wojtekmaj/react-date-picker#430]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

When i set portalContainer on DatePicker and set a value the calendar doesn't render in the HTML Element defined in portalContainer.

### Steps to reproduce

1. Create a ref to my div element `const ref = useRef<HTMLDivElement>(null);`
2. Add ref to my div `<div ref={ref} />`
3. Set value and portalContainer `<DatePicker
        value={new Date()}
        portalContainer={ref.current || undefined}
      />`

### Expected behavior

I expect to see the calendar in the div referenced.

### Actual behavior

The calendar isn't rendered in the div referenced.

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by wojtekmaj** [comment]
I'm unable to reproduce this, can you provide a CodeSandbox, perhaps?
