### ISSUE TITLE
Restricting the number of digits in any date format

### ISSUE THREAD

**Issue by sunnu0818** [wojtekmaj/react-date-picker#44]
For example If the date format is mm/dd/yyyy , is there a way to restrict the user to enter not more than two digits in mm , dd and not more than 4 digits in yyyy . As per the current version the user is allowed to enter any number of digits irrespective of date format and the user had to tab or click on next segment of the date.
It would be really helpful if you can address this issue.

Thanks
Sunaina

**Comment by wojtekmaj** [comment]
Hey Sunaina,
I think it's a great idea. Added to my backlog :)

**Comment by hholzmann16** [comment]
This would be a great addition, does anyone know of a workaround for this currently?

**Comment by maxxts** [comment]
> This would be a great addition, does anyone know of a workaround for this currently?

Agreed! I'm currently looking for a workaround for this as well. Any update would be appreciated!

**Comment by wojtekmaj** [comment]
Fixed in 0f2923a3742921d550d4c66b23e7da13cfb1fbd6
