### ISSUE TITLE
Option to disable date picker control

### ISSUE THREAD

**Issue by rp1214** [wojtekmaj/react-date-picker#45]
Can you please add the option to disable the control by exposing a prop 
something like disabled = {true} 
so that is becomes easy to handle the control based on the use cases

Currently i implemented a solution by setting pointer-events: none; but user can still tab through it and change using the keyboards

**Comment by wojtekmaj** [comment]
Oh wow, I'm amazed you are the first person to point that out. I'll do this soon!

**Comment by machiapply** [comment]
+1

**Comment by wojtekmaj** [comment]
All,
the feature has been implemented in v6.9.0

**Comment by rohitketkar87** [comment]
@wojtekmaj is it working in IE-11? For me, its greyed out but when i click on it, I am able to change it.

**Comment by wojtekmaj** [comment]
Hi @rohitketkar87, thanks for pointing that out - I can confirm there is an issue on IE caused by its non-standard behavior, being `focus` action being triggered on disabled elements. Fix is on the way.

**Comment by wojtekmaj** [comment]
@rohitketkar87, v6.10.1 is out. Let me know if it works for you.

**Comment by rohitketkar87** [comment]
@wojtekmaj Working now. Thanks.

**Comment by shivavelingker** [comment]
I am still able to change the date in Chrome if `disabled={true}`

**Comment by wojtekmaj** [comment]
@shivavelingker Which version are you on? I retested the whole suite and can't reproduce.

**Comment by shivavelingker** [comment]
@wojtekmaj This was a dumb mistake. I wrote a wrapper component for the date-picker, and forgot to pass the `disabled` prop properly, so it wasn't disabling. My mistake
