### ISSUE TITLE
Is there an event fired on Clear button click?

### ISSUE THREAD

**Issue by serge-eric-kalaga** [wojtekmaj/react-date-picker#450]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Please add an event when clicking on 'clear button'

**Comment by wojtekmaj** [comment]
When clicking clear icon, onChange is called with null.

**Comment by serge-eric-kalaga** [comment]
Thank

**Comment by phucdh410** [comment]
Thank you
