### ISSUE TITLE
Support Custom Input

### ISSUE THREAD

**Issue by brian-lim-42** [wojtekmaj/react-date-picker#47]
Hi,

Was wondering if there is appetite for a "customInput" property the same as in another project react-datepicker

This would allow for custom input boxes... for example integration with rmwc input boxes, etc.

If you think this is good, I will develop a PR for you

Thanks,
~ B

**Comment by wojtekmaj** [comment]
Hmmm... I'm okay with the idea, don't know what the community thinks about it. Anyway, with custom input, not much of the original react-date-picker is left - actually only the logic behind opening and closing the calendar. If there's a demand for that though I don't see a reason why not to.

**Comment by kpheasey** [comment]
@bhldev I needed an implementation using a single input that functioned like a regular input (onFocus/Blur/Change) etc.  This allows users to easily edit dates without changing inputs and responds to all regular input events.

https://gist.github.com/kpheasey/64fc79c656eede81fb4d651ebac70600

![screen shot 2018-04-09 at 1 09 10 pm](https://user-images.githubusercontent.com/3934075/38511774-3866cc22-3bf7-11e8-9861-b5fc68697d0c.png)

**Comment by wojtekmaj** [comment]
By the way, users don't need to change between the inputs to put the whole date in. If the date is separated by `.`, they can just press `.` and they will be in the next field. Arrow keys should work as well.

Probably in your case it can be also good to just un-hide the native input that is there for accessibility reasons, and hide the custom ones. That could work on modern browsers. But you'll need to use `appearance: textfield` to overwrite its default UI.

**Comment by 3mp3ri0r** [comment]
I actually need this feature right now

**Comment by hanyoureal** [comment]
I need this feature, the existing input is not customizable enough

**Comment by singleseeker** [comment]
when will the new version with this feature be published?
