### ISSUE TITLE
When placed in iframe, Calendar does not properly detect collisions with window edges

### ISSUE THREAD

**Issue by rudi-kit** [wojtekmaj/react-date-picker#488]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

We have a form with couple of date pickers. The form opens in the iframe. Height of the iframe is adjusted to height of the form. Iframe has the same host. When a datepicker is close to the screen bottom calendar hides under it. I prepared sample app, screenshot is attached.

### Steps to reproduce

I prepared sample [app](https://github.com/DBrutski/react-date-picker/tree/fit-in-iframe).
1. Run sample app in `sample/` directory
2. Goto localhost:3000
3. Open the datepicker in the screen bottom.

### Expected behavior

Calendar should open to up of the datepicker, so it doesn't hide under the screen.

### Actual behavior

Calendar hides under the screen.

### Additional information

![image](https://user-images.githubusercontent.com/12894128/207828336-5179e6ee-3ee0-4752-a26e-0e64374c0e01.png)

### Environment

- **Browser (if applicable)**: Chrome 108, Firefox 102
- **React-Date-Picker version**: 9.1.0
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
As far as I know there's no way for the iframe to "escape" its context and learn more about its own position, so figuring out collisions with window edges would not be easily possible. If you have any ideas on how to improve this, however, please contribute to react-fit - the package I'm using to position the calendar.
