### ISSUE TITLE
Integrate with redux-form?

### ISSUE THREAD

**Issue by cristian-sima** [wojtekmaj/react-date-picker#50]

**Comment by wojtekmaj** [comment]
Hey @cristian-sima, what would you like to know exactly? Looking briefly at their documentation, I think `<Field>` accepts custom components. Is there a problem you're facing?

**Comment by wojtekmaj** [comment]
@cristian-sima, I'm closing this issue to give more visibility to active issues, happy to reopen if this is something you'd still like to discuss.
