### ISSUE TITLE
Not able to show error message when invalid date entered dynamically.

### ISSUE THREAD

**Issue by DodiTank16** [wojtekmaj/react-date-picker#509]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

When I enter the date dynamically it shows only red background on a specific field like it may be a date, month, or year, but I want to show an error msg along with it on the other hand I'm not able to.

### Steps to reproduce

1. Go to: https://projects.wojtekmaj.pl/react-date-picker/
2. Click on: date in given in the center
3. Enter date dynamically: 00/00/0000

### Expected behavior

One must see or set an error msg when the entered date is less than then min date or the max date.

### Actual behavior

It only shows red background on a specific field in which one have entered invalid date like it may be a date, month, or year

### Additional information

![Invalid Date](https://user-images.githubusercontent.com/78642404/211258458-7b2dddd8-1ab1-4db3-8d49-86cadd9a2b41.png)

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**: 8.4.0
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
Use onInvalid to present a custom error, just like you normally would with any other input. Otherwise, an error will be shown in a popover upon submitting the form the input is in.

**Comment by bastian-hidalgo** [comment]
Hi @wojtekmaj could be awesome to include this information on Readme, thank you.

**Comment by AlbertCarreras** [comment]
Agree with @bastian-hidalgo here. There should be some prop in the API like "onError" that communicates the error externally. This is all managed internally. 

I'm having the following issues in this [codesandbox](https://c___)
- onInvalid doesn't work on invalid dates
- there's no popover communicating errors
- error handling is not in the [API table](https://github.com/wojtekmaj/react-date-picker) 

All it's left is the highlighted in red input. This is not good for accessibility as we are relying in color to communicate an error and we can customize error messaging as we don't have access to it.

**Comment by wojtekmaj** [comment]
v10.2.0 adds `onInvalidChange` prop which resolves this issue.
