### ISSUE TITLE
Re-implement MultiMonthView

### ISSUE THREAD

**Issue by DmytroSV** [wojtekmaj/react-date-picker#51]
Would be nice to have an old MultiMonthView feature, is it possible?

**Comment by wojtekmaj** [comment]
Hey @DmytroSV,
at the moment it is not possible, but it's a valueable feedback :) I'll keep it on my feature requests list.

**Comment by wojtekmaj** [comment]
This feature will be implemented with update of our dependency, React-Calendar, to v3.0.0, which is currently in beta.

**Comment by wojtekmaj** [comment]
This will not be worked on as this has little to do with native date input which React-Date-Picker tries to re-implement as closely as possible.

If you want to show multiple months at a time, I encourage you to try and experiment on your own using React-Calendar:

https://github.com/wojtekmaj/react-calendar/wiki/Upgrade-guide-for-React-Calendar-1.x-users#displaying-multiple-months
