### ISSUE TITLE
How to set data-testid prop? 

### ISSUE THREAD

**Issue by michal-wierzba** [wojtekmaj/react-date-picker#513]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I would like set data-testid for check is component disabled/enabled.
I reported that to react-datetime-picker, but I swear this is my last request about date-testid

Thank you

**Comment by wojtekmaj** [comment]
Implemented in 32ffe3a0dd12790521ce475291dd04a18c031c54.
