### ISSUE TITLE
Overflows when near the top of the page

### ISSUE THREAD

**Issue by jameskraus** [wojtekmaj/react-date-picker#52]
Fails to detect when an element goes right off the page:

![image](https://user-images.githubusercontent.com/415057/36740584-d99f3ea6-1bb0-11e8-93db-34c2a2a198d8.png)

This is a minor issue for me, but it occurred when the item was the first element on the page.

Repro repo:
https://github.com/jameskraus/react-date-picker-overflow

Just a guess, it may be if the page isn't large enough, a collision is detected at the bottom of the <body>, so the selector is moved above the input, but then it's hidden.

**Comment by jameskraus** [comment]
Maybe a good fix would be to take the selector's height, the body's top position, and check if the selector would be off screen if moved?

Edit: I did manage to get it to work, but due to complication of the logic being in the ref callback, I can only get it to work correctly once, then it will only appear below the component.

**Comment by wojtekmaj** [comment]
Hey @jameskraus,
the fix has been made and is going to be published with v6.8.3. I hope it will make it better in your situation; if not, please let me know and we'll work further.

**Comment by rohitketkar87** [comment]
Hi,
Experiencing the same issue in version 6.9.0
![overflow_issue](https://user-images.githubusercontent.com/20128493/37457201-a84c2a6c-2817-11e8-9ebe-183856acbde6.PNG)

**Comment by wojtekmaj** [comment]
Thanks. Currently it measures collisions between the calendar and `<body>`, clearly there's a room for improvement there. 
Workaround for now: If you have body set to width and height equal window size, and have scrollable content inside <body>, then it should work.
Will see what else I can do.
