### ISSUE TITLE
Warning / Bug with Vite v4

### ISSUE THREAD

**Issue by a-tonchev** [wojtekmaj/react-date-picker#530]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Vite 4 throws warning regarding the export of DatePicker.css

![image](https://user-images.githubusercontent.com/54528540/215786818-60f95fb0-65e1-4e4d-946d-317e4cf399fa.png)

### Steps to reproduce

Install vite@lates and run server with vite

### Expected behavior

Should not throw warning

### Actual behavior

Throws warning

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Doesn't look like it's coming from our side. We don't use `import * as …` in any CSS imports.
