### ISSUE TITLE
react-date-picker doesn't support in Internet Explorer

### ISSUE THREAD

**Issue by higordev223** [wojtekmaj/react-date-picker#54]
It works another browsers. But It's not work in IE11. The error is as follow.

"TypeError: Object doesn't support property or method 'isNaN'.

**Comment by wojtekmaj** [comment]
Fixed in v6.8.2. Thank you for reporting! Let me know if you find any other issues.

**Comment by rohitketkar87** [comment]
Hi,
Having one more issue in internet explorer. Dates are getting shown incorrectly. Days header (Sat, Sunetc) is correct but actual dates are wrong. PFA screenshot.
![image](https://user-images.githubusercontent.com/20128493/37459451-7cb42eb6-281e-11e8-8b9a-c74fc7e42b85.png)

**Comment by wojtekmaj** [comment]
Hey @rohitketkar87, you're affected by wojtekmaj/react-calendar#45 which has been fixed this very minute. Please update! You should get the new version of React-Calendar.

**Comment by rohitketkar87** [comment]
@wojtekmaj Thanks. Resolved now.
One more issue is there for which I have given comment on https://github.com/wojtekmaj/react-date-picker/issues/52.
