### ISSUE TITLE
edge case of value < minDate

### ISSUE THREAD

**Issue by manoogim** [wojtekmaj/react-date-picker#540]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Hi - my apologies in advance  if the following edge case is not in scope of this wonderful calendar.
The use case is that we have calendar with minDate constraint, and we have code which assigns 'value' of the calendar.
In other words, it's not a user who clicks to pick a date - it's code that does it.
For example, minDate is February 6 2023, and code assigns value February 2 2023.
If this was attempted as user interaction, it wouldn't be possible to do so.
But in case of API, if the caller doesn't check, and the widget doesn't check then we will be in inconsistent state, because value < minDate.

### Steps to reproduce

1. Create calendar with minDate={minDate}, value={maturityDate}
2. Write javascript that assigns maturityDate= February 2, 2023, minDate=February 6,2023
3. Run the script

### Expected behavior

value=undefined
// this outcome seems attractive, b/c it is saying 'I couldn't assign the value you want'

### Actual behavior

value=February 2, 2023
// this violates minDate constraint, and we have a calendar in bad state, and interactive behavior is different from API behavior

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by mimamulhassankhan** [comment]
Any update or workaround regarding this issue?
