### ISSUE TITLE
Old version of React-Date-Picker allows too new version of React-Calendar

### ISSUE THREAD

**Issue by LuisEgan** [wojtekmaj/react-date-picker#56]
I installed using:
`npm i react-date-picker@6.7.0`

With react 15.5.4

When I try to do the simple example:

```
state = {
    date: new Date(),
  }

  onChange = date => this.setState({ date })

  render() {
    return (
        <DatePicker
          onChange={this.onChange}
          value={this.state.date}
        />
   }
```

I get this error in the console:

![image](https://user-images.githubusercontent.com/19411549/37191142-99f87194-233c-11e8-8122-ff1c72c16b5c.png)

**Comment by wojtekmaj** [comment]
Hey there,
it seems like the version of react-calendar got installed. Which is odd, because it means package-lock.json did not work properly :(
Please try the following:
```
npm uninstall react-date-picker
npm install react-calendar@2.11.0
npm install react-date-picker@6.7.0
```

I think this will ensure the correct version of dependencies is installed.

**Comment by LuisEgan** [comment]
Thanks!
It turned out that the packages weren't installing correctly ( some windows errors ), fixed them and now it works like a charm :)

**Comment by wojtekmaj** [comment]
Happy to hear that! Don't hesitate to write if you have any other issues :)

**Comment by m-o-leary** [comment]
Hey there,

I installed (for React 15) version 6.7.0 and get this same issue.
I am using the library in an Electron app by the way.

I have the following versions installed:

``` 
    ...
    "react-calendar": "^2.11.0",
    "react-date-picker": "^6.7.0",
    ...
```

Using the following example:

```
import DatePicker from 'react-date-picker';
...
render(){
    return <DatePicker 
        onChange={this.onChange}
        value={this.state.date}
        locale="en-GB"
    />
}
```

I am getting the following:

![image](https://user-images.githubusercontent.com/24975408/40469995-835ffb0a-5f32-11e8-8910-ecee5f155a37.png)

npm install looks like the following:

![image](https://user-images.githubusercontent.com/24975408/40470048-a498edc2-5f32-11e8-8680-4d3b8b844c73.png)


any ideas?

**Comment by wojtekmaj** [comment]
Hmmm. I checked and it should work with react-calendar@2.12.0 even. It's the last version that used setLocale and exported it. Strange it did not work :(

**Comment by LuisEgan** [comment]
@buddythumbs are you sure everything installed correctly, both of the packages appear in your package.json?? Perhaps you could try deleting your `package-lock.json` and your `node_modules` folder and then running `npm install`

**Comment by m-o-leary** [comment]
Thanks for the help @LuisEgan - that got the library to load.

Now I am faced with no styling being imported - I will open/look for an issue

**Comment by dannyshaw** [comment]
package.json for `react-date-picker@6.7.0` has `"react-calendar": "^2.11.0"` (note the caret) There is no package-lock or yarn.lock.

A clean install (deleted node_modules) results in `react-calendar@2.16.1` to be installed and the call to `setLocale` fails as it does not exist.

I believe package.json should read:
```
"react-calendar": "~2.11.0"
```
Note the tilde

**Comment by wojtekmaj** [comment]
You are right. This should be as you wrote. I'll try and make a fix for you guys, but I don't know how long it will take for me to find the time.

For now you can use [Yarn selective version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to make it work without any fix.

**Comment by dannyshaw** [comment]
Just noting that this also doesn't work with `react-calendar@2.11.2`, the onChange handler never calls, so I've removed the tilde in my resolution and just pinning `2.11.0`. 

perhaps there was a bug at this version
https://github.com/wojtekmaj/react-calendar/compare/v2.11.0...v2.11.2

**Comment by wojtekmaj** [comment]
I reviewed the code and it doesn't look like it could break anything that is a browser environment. Happy to hear that my initial solution in one of the first comments worked for you!
