### ISSUE TITLE
Using .less from Yarn install

### ISSUE THREAD

**Issue by hyxos** [wojtekmaj/react-date-picker#57]
Hi there! I'm trying to integrate this into a project using .less instead of .css, I've added it using 'yarn add react-date-picker' but I can't figure out how to rebuild it when I got into node_modules/react-date-picker and change the `src/entry.js` to the .less instead of .css.

I've gotten it to work by editing the dist/entr.js file but i know that isn't the right way to do it.

Any insight would be greatly appreciated.

**Comment by wojtekmaj** [comment]
Hi,
as README.md states,you can do something like this:
```js
import DatePicker from 'react-date-picker/dist/entry.nostyle';
```
then, simply import LESS by yourself:
```js
import 'react-date-picker/dist/DatePicker.less';
```

and you should be ready to go!

**Comment by hyxos** [comment]
That is great, worked for me, thanks!

**Comment by hyxos** [comment]
Also, I imported the Calendar.less from react-calendar like this:
`import 'react-calendar/dist/Calendar.less'`
and I get that styling as well

**Comment by wojtekmaj** [comment]
Looks superb to me ;) Happy coding!
