### ISSUE TITLE
TypeScript build failure 

### ISSUE THREAD

**Issue by gadhlu02** [wojtekmaj/react-date-picker#579]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

As we know react-date-picker uses react-calendar internally, and react-calendar has made a new release with version 4.1.0.
 Because of that react-date-picker is not able to read the react-calender type props causing a build issue, this issue was not for react-calendar version 4.0.0. 

### Steps to reproduce

1)Install the latest version of react-date-picker
2)Try making react build out in your project 
3)System will through a build issue as seen below 

TS2322: Type '{ format: string; dayPlaceholder: string; monthPlaceholder: string; yearPlaceholder: string; "data-testid": any; openCalendarOnFocus: false; value: any; onChange: any; maxDate: Date; minDate: Date; }' is not assignable to type 'IntrinsicAttributes & DatePickerProps'.
  Property 'value' does not exist on type 'IntrinsicAttributes & DatePickerProps'.
    24 |         data-testid={props.testId}
    25 |         openCalendarOnFocus={false}
  > 26 |         value={props?.value}
       |         ^^^^^
    27 |         onChange={props?.onChange}
    28 |         maxDate={dt}
    29 |         minDate={minDt}

### Expected behavior

Build should be created without an error

### Actual behavior

Not able to create a build

### Environment

- **Browser (if applicable)**: Chrome
- **React-Date-Picker version**:9.2.0
- **React version**:18.2.0

**Comment by rossanodr** [comment]
I have the same problem with 
Type error: Type '{ onChange: (...event: any[]) => void; value: Date; }' is not assignable to type 'IntrinsicAttributes & DatePickerProps'.
10:02:41.379

**Comment by MustacheTuanVu** [comment]
@types/react-calendar version 4.0.0 and above has issues. So I downgraded the version of react-date-picker from 9.2.0 to 8.4.0. react-date-picker 8.4.0 used @types/react-calendar version 3.0.0. Worked for me.

**Comment by sas6757** [comment]
Similar problem

**Comment by wojtekmaj** [comment]
Sounds like a problem with React-Date-Picker types which seem to be incompatible with built-in, more accurate React-Calendar's one, causing build failure 🤔

**Comment by wojtekmaj** [comment]
I think it's going to be solved once React-Date-Picker becomes native TypeScript as well.

**Comment by sas6757** [comment]
And how long is the wait? Now I can’t put the latest version on the project, the component wrote on 9.0, but putting the same version on a new project, it gives this error, rolling back to version 8.4 - dist/entry.nostyle does not work

**Comment by wojtekmaj** [comment]
I'm providing updates on my free time with unsustainable funding so well typed package will released anywhere between now and 6 months or so.

I'm trying to migrate all packages I have to TypeScript to prevent exactly that.

I'm assuming some kind of hotfix can be provided for the already shipped major version, like fixing handwritten types or pinning React-Calendar version to 4.0.

**Comment by wojtekmaj** [comment]
Pushed a hotfix in v9.2.1, let me know if that's resolved for you!

**Comment by sas6757** [comment]
Thanks, it worked for me. If there is any error, I will write
