### ISSUE TITLE
value of date doesn't change when using minDate and maxDate properties

### ISSUE THREAD

**Issue by rohitketkar87** [wojtekmaj/react-date-picker#58]
Hi,
I have encountered a strange issue today. Consider following two screenshots. I have given condition that second one's minDate  = value of first one and when i change date in first one, second one should get defaulted to same date as first one.
![image](https://user-images.githubusercontent.com/20128493/37904653-72258cce-30ca-11e8-84c7-bde9dc6f925f.png)
![image](https://user-images.githubusercontent.com/20128493/37904679-84313fd0-30ca-11e8-8610-8fc8bc4ab429.png)
Now if I change date of first one to 3/22, second one's date also get changed to 3/22. PFB screenshots.
![image](https://user-images.githubusercontent.com/20128493/37904786-c2469842-30ca-11e8-8189-6ccb1e0b61e2.png)
![image](https://user-images.githubusercontent.com/20128493/37904802-cdd52ba6-30ca-11e8-898b-a913182fc6bb.png)
However, if I change date to 3/20 in first one second one's date doesn't get updated. PFB screenshots.
![image](https://user-images.githubusercontent.com/20128493/37904856-f776ed0a-30ca-11e8-8892-8ba64c8e4e72.png)
![image](https://user-images.githubusercontent.com/20128493/37904870-04fed1f4-30cb-11e8-962e-e0ce2a03ff99.png)
But if i click on second one (just click on calendar icon), date gets changed to 3/20.
![image](https://user-images.githubusercontent.com/20128493/37904922-2eb8697e-30cb-11e8-8f8d-c7046459ad49.png)
What I have observed is date is getting changed at backend but somehow its not getting reflected in datepicker.

**Comment by wojtekmaj** [comment]
So, if I understood you correctly:
Providing such minDate/maxDate that would overlap given value changes it, but changing minDate/maxDate so that it's no longer in conflict with value does not change it back to proper value

?

**Comment by rohitketkar87** [comment]
@wojtekmaj Yes i think you got it.
 Just to elaborate again, in above screenshots, if I change first one's date to 3/20, second one's date should also get changed to 3/20 which is not happening since I have also given condition minDate of second one = value of first one.

**Comment by falconvk** [comment]
I have a similar issue. Another input controls the allowed range of datepicker, as well as the currently selected value.
Changing the other input so datepicker's range (and value) moves forward(into future) works as intended and everything is updated accordingly.
However, changing the other input so datepicker's range and value move backwards in time, the values are correctly updated but date picker is stuck showing old data (also as red/invalid), until I at least open the calendar dropdown. When I open the calendar it gets updated.

**Comment by wojtekmaj** [comment]
@rohitketkar87's issue doesn't seem to exist anymore, tested this on my testing suite and everything appears to be in order. Adjusting either minDate or maxDate and clearing it/setting to non-conflicting value would bring back the original value.

I'd appreciate a minimal reproduction repo, perhaps in something like Code Sandbox.
