### ISSUE TITLE
Support for defaultValue

### ISSUE THREAD

**Issue by agnieszka-puzio** [wojtekmaj/react-date-picker#586]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Is there a chance for supporting defaultValue? I saw this PR: https://github.com/wojtekmaj/react-date-picker/pull/211 but it looks abandoned.

**Comment by wojtekmaj** [comment]
Hi!
This PR indeed is long forgotten but this matter surely deserves another go. I can't give you any timeline though as I'm only developing this on my free time.

**Comment by aseerkt** [comment]
@wojtekmaj Can you assign this task to me with some possible directions?
