### ISSUE TITLE
Type 'Dispatch<SetStateAction>' is not assignable to type '(value: Value) => void'.

### ISSUE THREAD

**Issue by johannessorheim** [wojtekmaj/react-date-picker#607]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

After upgrade to version 10.0.3, typescript started to complain about types:
![image](https://user-images.githubusercontent.com/8747772/235138175-1ae78a37-8c9e-4b7e-81c5-50ee9b7c96e7.png)

Type 'Dispatch<SetStateAction<Date>>' is not assignable to type '(value: Value) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'Value' is not assignable to type 'SetStateAction<Date>'.
      Type 'null' is not assignable to type 'SetStateAction<Date>'.ts(2322)

### Steps to reproduce

Upgrade from version 10.0.1 to version 10.0.3

### Expected behavior

Typescript compiles

### Actual behavior

Typescript complain

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**: 10.0.3
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
You will get null in onChange when clearing the value. Type it explicitly:

```ts
... useState<Date | [Date, Date] | null>(...)
```

You will also get an array if you use returnValue prop to do so, so you may need to account for that (I think there's a room for improvement in types here).

See full example:

https://github.com/wojtekmaj/react-date-picker/blob/main/sample/Sample.tsx#L6-L8
