### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by abaksha-sc** [wojtekmaj/react-date-picker#615]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Online demo link is not working

![image](https://github.com/wojtekmaj/react-date-picker/assets/37663273/0d95f5a0-2307-4140-b1f6-cc3b3da960f0)

### Steps to reproduce

Go to https://projects.wojtekmaj.pl/react-date-picker/

### Expected behavior

Any online demo link in readme to just view how it looks

### Actual behavior

See screenshot in description

### Environment

- **Browser (if applicable)**: Chrome 113.0.5672.127
- **React-Date-Picker version**: [v10.2.0](https://github.com/wojtekmaj/react-date-picker/releases/tag/v10.2.0)

**Comment by wojtekmaj** [comment]
Traffic from Russia and Belarus is blocked at the moment.
