### ISSUE TITLE
Directly control the direction of the pop up?

### ISSUE THREAD

**Issue by jmathew** [wojtekmaj/react-date-picker#62]
I ran into a situation where the picker popped up above the input even though there was no room in that direction.

Looking at the code it looks like the direction the picker is computed based on overflow involving the body element. 

In my case the the body element was at height 0. The picker was inside a modal that was positioned fixed and was the full height and width of the view port. The picker detected an overflow and decided to pop up on top of the input, even though it was already at the top position of my modal. 

I worked around this by overriding the class:
```
.calander {
        top: 100%;
        bottom:auto;
    }
<DatePicker calendarClassName={"calendar"} ... />
```

I think it would be helpful if we could control the direction of the pop up in someway. 

A direct override would be simplest. Something like `PopupBehavior: 'auto | top | bottom'`.

Alternatively, there could be a callback prop for computing the position.

**Comment by IAmAshishNegi** [comment]
Is it implemented?

**Comment by wojtekmaj** [comment]
No, it's not, but #126 is going to make it a lot easier.
