### ISSUE TITLE
If input value is less than mindate mindate is shown

### ISSUE THREAD

**Issue by sansiven** [wojtekmaj/react-date-picker#639]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

I am developing an application which utilises the ability to set date to start a certain operation. I am also providing a min value. A use case occured when the DatePicker has value set in the past and min date set to present. I expected the value to be shown as what has been passed to the Datepicker but it is showing the min date.

### Steps to reproduce

- Give the value prop to be yesterday's date
- give minDate prop to be today's date

### Expected behavior

- the value should be shown as actual value i.e. yesterday on the input
- when opening the calendar to pick the date, it should show the dates only after today's

### Actual behavior

- the value is not the passed value prop but the minDate prop

### Environment

- **React-Date-Picker version**: 10.0.3
- **React version**: 18.2.0

**Comment by shuoO-24** [comment]
Hi @sansiven. I'm looking through this issue, but I'm wondering why you want the actual date shown as the value when the actual date is less than the min date you've set. The values should not be greater than min date and min date is the minimum value. I think current logic makes sense to me.

**Comment by jfilipeferreira96** [comment]
This is indeed a pain in the butt. The input placeholder will read the minDate value instead of the actual value which is lower than the minDate.

I did the following, however I don't think this can help everyone.
minDate={new Date(expiration.date) < new Date() ? new Date(expiration.date) : new Date()}

**Comment by jfilipeferreira96** [comment]
> Hi @sansiven. I'm looking through this issue, but I'm wondering why you want the actual date shown as the value when the actual date is less than the min date you've set. The values should not be greater than min date and min date is the minimum value. I think current logic makes sense to me.

Picture a feature for adding/editing cards. Let's say you set a card to expire on 2023-01-01 with minDate = {newDate()}. However, upon opening the editing page on 2023-01-31, the value displayed in the react-date-picker input will match the minDate, which doesn't align with the actual data stored in the database.
