### ISSUE TITLE
Add onFocus & onBlur events

### ISSUE THREAD

**Issue by baffleinc** [wojtekmaj/react-date-picker#64]
We are using react-date-picker (love it) in combination with react-redux-forms. In order to make it play right with validation we need to hook into the onClick (focus) and click outside the component (blur). 

Passing onClick to the component does nothing - just gets ignored. 

recreate:
`<DatePicker onClick={() => console.log('hello')} />; // never fires`.

Do you know a potential workaround for this?

**Comment by wojtekmaj** [comment]
Hmmm. That seems like an excellent idea! My main concern is how to handle this nicely taking into consideration that `DatePicker` renders `DateInput` and `Calendar` components, both potentially supporting a number of events. I could catch all the events that bubbled up to `DatePicker`, but is it an optimal solution?

**Comment by baffleinc** [comment]
We were concerned with the actual text input itself, not the DateInput or Calendar components.

**Comment by yyynnn** [comment]
Maybe a simple render prop to render custom input field would to the trick.

    <StyledDatePicker
      name={input.name}
      errorOffset={errorDimensions.height}
      error={error}
      value={date}
      clearIcon={null}
      maxDate={today}
      render={props=> (<CustomInputField
                                       {...props}       
                                       onChange={input.onChange}
                                       onFocus={input.onFocus}
                                       onBlur={input.onBlur}) />
    />

**Comment by yyynnn** [comment]
so will you add events? this is crucial

**Comment by wojtekmaj** [comment]
Starting with v6.13.0, you are able to do this.
