### ISSUE TITLE
react-date-picker 10.0.0 accidentally pushed to npmjs as 9.3.0?

### ISSUE THREAD

**Issue by jeffmahoney** [wojtekmaj/react-date-picker#645]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Hello -

I have a project that is using react-date-picker 9.x. This past week, it was updated on npmjs.org to 9.3.0 -- but there isn't a 9.3.0 tag in the Github repo. It turns out that it's actually 10.0.0 with a different version value.

This is causing my project to warn on build with:
```
"react-date-picker/dist/DateInput/DayInput" is imported by "react-date-picker/dist/DateInput/DayInput?commonjs-external", but could not be resolved – treating it as an external dependency.
```
... and others.

### Steps to reproduce

```
$ curl -L -O https://registry.npmjs.org/react-date-picker/-/react-date-picker-9.2.0.tgz
$ tar zxf react-date-picker-9.2.0.tgz 
$ mv package package-9.2.0
$ curl -L -O https://registry.npmjs.org/react-date-picker/-/react-date-picker-9.3.0.tgz
$ tar zxf react-date-picker-9.3.0.tgz 
$ mv package package-9.3.0
$ curl -L -O https://registry.npmjs.org/react-date-picker/-/react-date-picker-10.0.0.tgz
$ tar zxf react-date-picker-10.0.0.tgz 
$ mv package package-10.0.0

$ diff -ruNp package-9.3.0/ package-10.0.0/ 
diff -ruNp package-9.3.0/package.json package-10.0.0/package.json
--- package-9.3.0/package.json
+++ package-10.0.0/package.json
   "name": "react-date-picker",
-  "version": "9.3.0",
+  "version": "10.0.0",
   "description": "A date picker for your React app.",
   "main": "dist/cjs/index.js",
   "module": "dist/esm/index.js",

$ diff -ruNp package-9.[23].0
# ~14000 lines
```

### Expected behavior

That 9.x is actually 9.x

### Actual behavior

9.3.0 is 10.0.0

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by wojtekmaj** [comment]
What the... :D Yes, you're right, that must have slipped through by accident! 

npm does not allow removing old packages, but allows deprecating them, so that's what I did to v9.3.0.

Thanks, great catch!
