### ISSUE TITLE
issue with leap year while typing

### ISSUE THREAD

**Issue by kumarrsk** [wojtekmaj/react-date-picker#659]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Hi,
I have set the date format on my date picker as MM/dd/yyyy.
However, when the user writes a date in the input, for example 02/29/200 , the date picker value becomes 03/01/200 , so it looks like the date format is still the original for the user input.
Has anyone had this issue before and knows a solution?

### Steps to reproduce

change the format to MM/dd/yyyy
type 02/29/200
it will change to 03/01/200

### Expected behavior

till needs to wait to add complete year 

### Actual behavior

changing the date to next day 

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by dagjomar** [comment]
This is still an issue in version `10.6.0` which is causing a problem for us.

**Comment by dagjomar** [comment]
Pull request with fix sent: https://github.com/wojtekmaj/react-date-picker/pull/695

@kumarrsk you might want to comment on that and improve chances to get it merged

**Comment by ijverig** [comment]
We are also having some problems with this leap year validation.
Steps to reproduce are the same.
Would be awesome if this got merged.
