### ISSUE TITLE
March and June are showing extra days breaking the layout

### ISSUE THREAD

**Issue by cr-eative-dev** [wojtekmaj/react-date-picker#662]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

<img width="341" alt="Bildschirmfoto 2024-05-07 um 09 55 43" src="https://github.com/wojtekmaj/react-date-picker/assets/13886141/f22325dc-21aa-4e03-b7f9-6d2429c39a7c">
<img width="319" alt="Bildschirmfoto 2024-05-07 um 09 55 49" src="https://github.com/wojtekmaj/react-date-picker/assets/13886141/64255919-fdf9-4e24-b3f5-797872182454">

Only march and june showing so many extra days breaking the layout of the time box

<img width="376" alt="Bildschirmfoto 2024-05-07 um 09 57 05" src="https://github.com/wojtekmaj/react-date-picker/assets/13886141/4e035f44-dec8-497a-89aa-990f75139e5e">

### Steps to reproduce

Its already on the website like this: https://reactdatepicker.com/

### Expected behavior

It should only show the normal 31 days not breaking the layout

### Actual behavior

It shows extra days in june and march breaking for example the time select layout

### Environment

- **Browser (if applicable)**:
- **React-Date-Picker version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Wrong repo
