### ISSUE TITLE
Enter is not working on use manual date input

### ISSUE THREAD

**Issue by croschel** [wojtekmaj/react-date-picker#664]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

Basically when we are using the input of date picker instead clicking on calendar icon and we press enter nothing happens. Obs: Esc key is working normally (closing the calendar component).

### Steps to reproduce

1. Click on a datepicker input (day, month or year input) rendered on the screen;
2. After add new date with calendar or not press enter;
<img width="367" alt="Screenshot 2024-05-29 at 12 45 18" src="https://github.com/wojtekmaj/react-date-picker/assets/36478774/345626ad-c7db-454a-8a2c-ec7dbc46fe1c">

### Expected behavior

The Calendar should be closed.

### Actual behavior

The calendar still there.

### Environment

- **Browser (if applicable)**: All Browsers
- **React-Date-Picker version**: 11.0.0
- **React version**: 18.2.0

**Comment by aaronlifton** [comment]
Also seeing this behavior. Would be ideal to close the calendar when `enter` is pressed after typing the full date.
