### ISSUE TITLE
Should a click event on the root element open the calendar?

### ISSUE THREAD

**Issue by Zertz** [wojtekmaj/react-date-picker#67]
I'm thinking this should be the default behavior but perhaps there's a reason not to this?

**Comment by wojtekmaj** [comment]
Hmmm, not sure what would be the benefit from it. Calendar opens whenever you focus on an input or manually click calendar toggle button. Is some case not covered by these actions?

**Comment by Zertz** [comment]
I switched to using `calendarIcon` as intended and it works fine! 💯
