### ISSUE TITLE
TypeError: Failed to resolve module specifier "react-date-picker/dist/DateInput". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by DonSmog** [wojtekmaj/react-date-picker#679]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Date-Picker version
- [X] I have checked if this bug is not already reported

### Description

In one of my vite projects, I'm using @wojtekmaj/react-daterange-picker v4.2.1 which requires react-date-picker (I used v9.1.0). Everything works fine on local but on serve of the build, I get this error
![image](https://github.com/user-attachments/assets/f267c7d3-82a4-4db3-a3ad-9807f6c4ac13)

I've searched everywhere but can't find a solution to this.

### Steps to reproduce

Create a vite-react application and add @wojtekmaj/react-daterange-picker v4.2.1 and  react-date-picker as dependencies. Run yarn build and yarn serve and preview the page

### Expected behavior

@wojtekmaj/react-daterange-picker should not require "import "react-date-picker/dist/DatePicker.css";"

### Actual behavior

The above error occured

### Environment

- **Browser (if applicable)**: Chrome
- **React-Date-Picker version**: 9.1.0
- **React version**: 18.3.0

**Comment by wojtekmaj** [comment]
Consider updating to the latest version; I'm not able to support 3 major versions back.
