### ISSUE TITLE
Add showLeadingZeros prop to DatePickerProps

### ISSUE THREAD

**Issue by u3k** [wojtekmaj/react-date-picker#70]
This property is not exposed by CalendarProps interface

**Comment by wojtekmaj** [comment]
Hmm, I'm confused, shouldn't it be directly in DatePicker's interface? Also I noticed it's missing from documentation so thanks for heads up!

**Comment by u3k** [comment]
My bad, yes! This should be in DatePickerProps, for sure! :) Thanks for dealing with this one.

**Comment by wojtekmaj** [comment]
Hey @u3k, could you please verify if index.d.ts now looks okay on master? I'd like someone more experienced with TypeScript to have a glance before I release new version. Thanks in advance!

**Comment by wojtekmaj** [comment]
Fixed, will be released in 6.10.2.
