### ISSUE TITLE
Calendar navigation doesn't work.

### ISSUE THREAD

**Issue by Ebuall** [wojtekmaj/react-date-picker#74]
Wasted a bit of time, before discovered, it's a calendar bug https://github.com/wojtekmaj/react-calendar/issues/75. Specifying versions like this and adding react-calendar explicitly resolves the issue:
```
    "react-calendar": "2.13.5",
    "react-date-picker": "6.9.1",
```

**Comment by wojtekmaj** [comment]
Thanks for the update. I released new version of React-Calendar which should resolve the issue.

Please refer to wojtekmaj/react-calendar#78 for official recommended way of fixing the issue.

**Comment by froziq** [comment]
Hello!
Help me please. How can i fix this bug with `react-date-picker` /  `react-datetime-picker` ? 
I don't use `react-calendar` directly.
I tried to upgrade each of packages, but its unsuccessfully.

**Comment by wojtekmaj** [comment]
Hello,
v6.10.2 just has been released and it should guarantee to work fine with React 16.4. Previously you may have needed to reinstall package for it to work correctly (it had to download the newest version of react-calendar, now it's required to do so). Let me know if it works for you!
