### ISSUE TITLE
IE browser display issue

### ISSUE THREAD

**Issue by stileszhong** [wojtekmaj/react-date-picker#79]
hi, @wojtekmaj, does react-date-picker support IE browser?
my IE version is 11.0.9600, and when i use props **locale="zh-cn"** , in chrome is work well,
in IE, only 2018 display, month and day is not display.
can you have a look about this? 
thanks.
![bug](https://user-images.githubusercontent.com/41105811/42556535-7cfd3d42-851e-11e8-9526-0e85973b52d6.png)

**Comment by wojtekmaj** [comment]
Hey there,
React-Date-Picker relies on Intl.DateTimeFormat. Basically, it pushes the responsibility for figuring out the date format to the browser. That's the secret why it's so light and still supports more locales than any other :)

On legacy browsers like Internet Explorer, Intl polyfill may help as stated in README.

**Comment by wojtekmaj** [comment]
By the way: it seems like you need a date range. Have a look at wojtekmaj/React-DateRange-Picker repository :)

**Comment by wojtekmaj** [comment]
@stileszhong Would you mind having a look if that problem is still happening? A lot of bugs related to non-latin locales were closed recently. I'll be happy to reopen and investigate if you're still facing this issue.
