### ISSUE TITLE
Component Not Exported Issue

### ISSUE THREAD

**Issue by EcorrDev** [wojtekmaj/react-date-picker#80]
I have a react error when I try to use the DatePicker component : 
![image](https://user-images.githubusercontent.com/16755777/42568142-680402de-850c-11e8-8649-abd72208dc75.png)

My package.json file : 
![image](https://user-images.githubusercontent.com/16755777/42568183-8c3710e2-850c-11e8-98b6-3d1671112384.png)

My component using DatePicker : 
![image](https://user-images.githubusercontent.com/16755777/42568226-b065c8b4-850c-11e8-8ed4-885a93a0c8f9.png)

![image](https://user-images.githubusercontent.com/16755777/42568236-bf45fd22-850c-11e8-891e-b2cee1e186c9.png)

Is there a way to fix it ?

**Comment by wojtekmaj** [comment]
As stated in README, `import DatePicker from 'react-date-picker'`. It's a default export.
