### ISSUE TITLE
"range" is an invalid prop for "returnValue"

### ISSUE THREAD

**Issue by B-Reif** [wojtekmaj/react-date-picker#81]
Issue type: **bug**
The [documentation](https://github.com/wojtekmaj/react-date-picker#props) lists "range" as a possible value for `returnValue`, but it fails the propTypes check.

To reproduce:
Render a `Datepicker` element with `returnValue` set to "range".

Expected outcome:
Datepicker renders without errors and enables selection of a range of values to be returned.

Actual outcome:
When rendering, Datepicker throws a propTypes error.

```Failed prop type: Invalid prop `returnValue` of value `range` supplied to `DateInput`, expected one of ["start","end"].```

When selecting a date, the Datepicker returns an array of two dates as expected, but their values are both set to the same day. Selecting an actual range of dates does not work.

**Comment by wojtekmaj** [comment]
Hello,
thanks for pointing that out! Just fixed that. Will be a part of the next release, be it major or minor :)
