### ISSUE TITLE
In Preact, I'm getting an error "Cannot read property 'appendChild' of null"

### ISSUE THREAD

**Issue by kesha-antonov** [wojtekmaj/react-date-picker#84]
See ```container.appendChild(span);``` in ```utils.js```

![screen shot 2018-07-26 at 11 42 13](https://user-images.githubusercontent.com/11584712/43251626-169909ee-90c9-11e8-93dd-165ceffd1adf.png)

**Comment by wojtekmaj** [comment]
Hello,
while Preact is not officially supported it would be nice if it was working with it.

Are you getting this consistently or in specific situation? In React, there's no possibility that a mounted component doesn't have parentElement, so this would never happen, I suppose.

This is an interesting case that Preact creators may be interested in.

If you know Preact better than me, feel free to create a PR including a fix, if you know how to fix this without breaking it on React.

**Comment by kesha-antonov** [comment]
I suppose I should have had to include your script in the end of body
