### ISSUE TITLE
Bug in renderCalendar

### ISSUE THREAD

**Issue by qens** [wojtekmaj/react-date-picker#88]
`    renderCalendar() {
           ........
          if (collisions.collidedBottom) {
            const overflowTopAfterChange = (
              collisions.overflowTop + ref.clientHeight + this.wrapper.clientHeight
            );
`
this.wrapper is not initialized yet, because renderCalendar invokes right inside render method...

**Comment by wojtekmaj** [comment]
What is your issue? What are the steps to reproduce?

**Comment by noashka** [comment]
When we come inside collisions.collidedBottom condition, we have this.wrapper as undefined and have error Uncaught TypeError: Cannot read property 'clientHeight' of undefined

**Comment by wojtekmaj** [comment]
Ok, so that's being handled in #112, so I'm gonna close this issue.

**Comment by wojtekmaj** [comment]
Duplicate of #112
