### ISSUE TITLE
The build/ folder isn't published! Version 6.2.1 is broken!

### ISSUE THREAD

**Issue by marcofugaro** [wojtekmaj/react-date-picker#9]
Hey, somehow on your latest publish the build folder to which points the library when you require it isn't there --> `"main": "build/entry.js",`. 

Maybe is it because `build` is in the .npmignore, or because the `prepublishOnly` hook didn't work?

Please publish a patch as soon as possible, for the future maybe include the build in the repo, I think it's safer and many other libraries do it. Or use the `files` field in package.json to publish only the `build` folder.

**Comment by wojtekmaj** [comment]
Thanks, I'm on it. Strange, it used to work perfectly.

**Comment by wojtekmaj** [comment]
Fixed in 6.2.2. Thanks so much!

**Comment by marcofugaro** [comment]
Thank you for being so quick!

**Comment by wojtekmaj** [comment]
FYI it's still publishing, I'm rescuing it on another computer. Please give me 10 minutes tops!

**Comment by marcofugaro** [comment]
6.2.1 is still the latest version on npm?
https://www.npmjs.com/package/react-date-picker
Can't update it

**Comment by marcofugaro** [comment]
Sure thing! No prob!

**Comment by wojtekmaj** [comment]
@marcofugaro You should have 6.2.2 published and 6.2.1 marked as deprecated. I manually checked package contents and build folder is back in place. Please confirm whether everything works fine for you.

**Comment by marcofugaro** [comment]
Updated it just now, it works fine! Thank you!
