### ISSUE TITLE
Add a prop to hide the clear icon

### ISSUE THREAD

**Issue by adityatandon007** [wojtekmaj/react-date-picker#98]
Hi @wojtekmaj . Can I remove that clear icon that is present by default in datepicker. I don't want to show that ` x` icon in my case. Is there any prop to disable that icon. It would be super helpful.
Here is a screenshot:
![screenshot from 2018-09-11 15-39-39](https://user-images.githubusercontent.com/25108385/45353711-36fed080-b5d9-11e8-9347-83843b745891.png)

**Comment by adityatandon007** [comment]
Sorryy for troubling you. I just turned the display to none in css. Let me know if there is a prop available to disable it. Would be nice to check that too. Feel free to comment and close this if it is something that might be availalbe in future release.

**Comment by wojtekmaj** [comment]
While your solution is perfectly okay, I agree there should be a way to disable it just like you can with other icons. I'll do that!

**Comment by wojtekmaj** [comment]
Just checked - setting `clearIcon={null}` will remove the icon completely. Documentation will be updated to make it clearer.

**Comment by Misbah-Mushtaq** [comment]
> Just checked - setting `clearIcon={null}` will remove the icon completely. Documentation will be updated to make it clearer.

I tried same thing but it is not working :/ @wojtekmaj

**Comment by ashu-mudrex** [comment]
What if I want hide the icon conditionally?
Like view the icon if a certain condition is met or else hide it? 
What will be default value for this prop?

**Comment by wojtekmaj** [comment]
Please don't dig up 5-year old issues and use discussions for questions.
