### ISSUE TITLE
Invalid date format for zh-CN locale in IE

### ISSUE THREAD

**Issue by AnveshR7** [wojtekmaj/react-date-picker#99]
for the Translations in **IE** for Chinese, the input is showing only the year.

![chinese](https://user-images.githubusercontent.com/43156710/45365562-c3de6580-b5aa-11e8-91d5-d8cfdbb01546.JPG)

**Comment by wojtekmaj** [comment]
This has to do with `new Intl.DateTimeFormat('zh-CN', { day: 'numeric', month: 'numeric', year: 'numeric' }).format(new Date())` returning `"‎2018‎年‎9‎月‎11‎日"` and not `"2018/9/11"` like other browsers.

Fixing this in the next release.

**Comment by AnveshR7** [comment]
Thanks @wojtekmaj

**Comment by wojtekmaj** [comment]
Fixed in 6.12.1

**Comment by AnveshR7** [comment]
Thank You @wojtekmaj for quick fix
